// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_clamped_hebrew_date`, `java_holiday_index_to_rust`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FINDER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Find the timezone for a given longitude and latitude
String findTimezone({required double longitude, required double latitude}) =>
    RustLib.instance.api
        .crateApiFindTimezone(longitude: longitude, latitude: latitude);

/// Get all the timezones supported by the library
List<String> timezones() => RustLib.instance.api.crateApiTimezones();

/// Calculate a zman at a given location and date
(String, PlatformInt64)? calculateZman(
        {required PlatformInt64 ateretTorahSunsetOffsetMinutes,
        required PlatformInt64 candleLightingOffsetMinutes,
        required bool useAstronomicalChatzosForOtherZmanim,
        required double latitude,
        required double longitude,
        required double elevation,
        required String timezone,
        required PlatformInt64 randomYear,
        required PlatformInt64 randomMonth,
        required PlatformInt64 randomDay,
        required bool useElevation,
        required ZmanimPreset zman}) =>
    RustLib.instance.api.crateApiCalculateZman(
        ateretTorahSunsetOffsetMinutes: ateretTorahSunsetOffsetMinutes,
        candleLightingOffsetMinutes: candleLightingOffsetMinutes,
        useAstronomicalChatzosForOtherZmanim:
            useAstronomicalChatzosForOtherZmanim,
        latitude: latitude,
        longitude: longitude,
        elevation: elevation,
        timezone: timezone,
        randomYear: randomYear,
        randomMonth: randomMonth,
        randomDay: randomDay,
        useElevation: useElevation,
        zman: zman);

/// Get all the ZmanimPresets supported by the library
List<ZmanimPreset> presets() => RustLib.instance.api.crateApiPresets();

(int, int, int)? jewishDateToGregorianDate(
        {required int year, required int month, required int day}) =>
    RustLib.instance.api
        .crateApiJewishDateToGregorianDate(year: year, month: month, day: day);

(int, int, int)? gregorianDateToJewishDate(
        {required int year, required int month, required int day}) =>
    RustLib.instance.api
        .crateApiGregorianDateToJewishDate(year: year, month: month, day: day);

(int, int, int)? addDaysToJewishDate(
        {required int year,
        required int month,
        required int day,
        required PlatformInt64 daysToAdd}) =>
    RustLib.instance.api.crateApiAddDaysToJewishDate(
        year: year, month: month, day: day, daysToAdd: daysToAdd);

(int, int, int)? addMonthsToJewishDate(
        {required int year,
        required int month,
        required int day,
        required int monthsToAdd}) =>
    RustLib.instance.api.crateApiAddMonthsToJewishDate(
        year: year, month: month, day: day, monthsToAdd: monthsToAdd);

(int, int, int)? addYearsToJewishDate(
        {required int year,
        required int month,
        required int day,
        required int yearsToAdd}) =>
    RustLib.instance.api.crateApiAddYearsToJewishDate(
        year: year, month: month, day: day, yearsToAdd: yearsToAdd);

void testJewishCalendar(
        {required int year,
        required int month,
        required int day,
        required bool inIsrael,
        required bool useModernHolidays,
        required JavaJewishCalendarTestResults java}) =>
    RustLib.instance.api.crateApiTestJewishCalendar(
        year: year,
        month: month,
        day: day,
        inIsrael: inIsrael,
        useModernHolidays: useModernHolidays,
        java: java);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>
abstract class ZmanimPreset implements RustOpaqueInterface {
  /// Get the name of the ZmanimPreset
  /// This is also the method name in the Java side
  String name();
}

class JavaJewishCalendarTestResults {
  final bool isBirkasHachamah;
  final int? getParshah;
  final int getUpcomingParshah;
  final int? getSpecialShabbos;
  final int getYomTovIndex;
  final bool isAssurBemelacha;
  final bool hasCandleLighting;
  final bool isAseresYemeiTeshuva;
  final bool isYomKippurKatan;
  final bool isBeHaB;
  final bool isTaanisBechoros;
  final int? getDayOfChanukah;
  final bool isRoshChodesh;
  final bool isMacharChodesh;
  final bool isShabbosMevorchim;
  final int? getDayOfOmer;

  const JavaJewishCalendarTestResults.raw({
    required this.isBirkasHachamah,
    this.getParshah,
    required this.getUpcomingParshah,
    this.getSpecialShabbos,
    required this.getYomTovIndex,
    required this.isAssurBemelacha,
    required this.hasCandleLighting,
    required this.isAseresYemeiTeshuva,
    required this.isYomKippurKatan,
    required this.isBeHaB,
    required this.isTaanisBechoros,
    this.getDayOfChanukah,
    required this.isRoshChodesh,
    required this.isMacharChodesh,
    required this.isShabbosMevorchim,
    this.getDayOfOmer,
  });

  factory JavaJewishCalendarTestResults(
          {required bool isBirkasHachamah,
          int? getParshah,
          required int getUpcomingParshah,
          int? getSpecialShabbos,
          required int getYomTovIndex,
          required bool isAssurBemelacha,
          required bool hasCandleLighting,
          required bool isAseresYemeiTeshuva,
          required bool isYomKippurKatan,
          required bool isBeHaB,
          required bool isTaanisBechoros,
          int? getDayOfChanukah,
          required bool isRoshChodesh,
          required bool isMacharChodesh,
          required bool isShabbosMevorchim,
          int? getDayOfOmer}) =>
      RustLib.instance.api.crateApiJavaJewishCalendarTestResultsNew(
          isBirkasHachamah: isBirkasHachamah,
          getParshah: getParshah,
          getUpcomingParshah: getUpcomingParshah,
          getSpecialShabbos: getSpecialShabbos,
          getYomTovIndex: getYomTovIndex,
          isAssurBemelacha: isAssurBemelacha,
          hasCandleLighting: hasCandleLighting,
          isAseresYemeiTeshuva: isAseresYemeiTeshuva,
          isYomKippurKatan: isYomKippurKatan,
          isBeHaB: isBeHaB,
          isTaanisBechoros: isTaanisBechoros,
          getDayOfChanukah: getDayOfChanukah,
          isRoshChodesh: isRoshChodesh,
          isMacharChodesh: isMacharChodesh,
          isShabbosMevorchim: isShabbosMevorchim,
          getDayOfOmer: getDayOfOmer);

  @override
  int get hashCode =>
      isBirkasHachamah.hashCode ^
      getParshah.hashCode ^
      getUpcomingParshah.hashCode ^
      getSpecialShabbos.hashCode ^
      getYomTovIndex.hashCode ^
      isAssurBemelacha.hashCode ^
      hasCandleLighting.hashCode ^
      isAseresYemeiTeshuva.hashCode ^
      isYomKippurKatan.hashCode ^
      isBeHaB.hashCode ^
      isTaanisBechoros.hashCode ^
      getDayOfChanukah.hashCode ^
      isRoshChodesh.hashCode ^
      isMacharChodesh.hashCode ^
      isShabbosMevorchim.hashCode ^
      getDayOfOmer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JavaJewishCalendarTestResults &&
          runtimeType == other.runtimeType &&
          isBirkasHachamah == other.isBirkasHachamah &&
          getParshah == other.getParshah &&
          getUpcomingParshah == other.getUpcomingParshah &&
          getSpecialShabbos == other.getSpecialShabbos &&
          getYomTovIndex == other.getYomTovIndex &&
          isAssurBemelacha == other.isAssurBemelacha &&
          hasCandleLighting == other.hasCandleLighting &&
          isAseresYemeiTeshuva == other.isAseresYemeiTeshuva &&
          isYomKippurKatan == other.isYomKippurKatan &&
          isBeHaB == other.isBeHaB &&
          isTaanisBechoros == other.isTaanisBechoros &&
          getDayOfChanukah == other.getDayOfChanukah &&
          isRoshChodesh == other.isRoshChodesh &&
          isMacharChodesh == other.isMacharChodesh &&
          isShabbosMevorchim == other.isShabbosMevorchim &&
          getDayOfOmer == other.getDayOfOmer;
}
