// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FINDER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Find the timezone for a given longitude and latitude
String findTimezone({required double longitude, required double latitude}) =>
    RustLib.instance.api
        .crateApiFindTimezone(longitude: longitude, latitude: latitude);

/// Get all the timezones supported by the library
List<String> timezones() => RustLib.instance.api.crateApiTimezones();

/// Calculate a zman at a given location and date
(String, PlatformInt64)? calculateZman(
        {required PlatformInt64 ateretTorahSunsetOffsetMinutes,
        required PlatformInt64 candleLightingOffsetMinutes,
        required bool useAstronomicalChatzosForOtherZmanim,
        required double latitude,
        required double longitude,
        required double elevation,
        required String timezone,
        required PlatformInt64 randomYear,
        required PlatformInt64 randomMonth,
        required PlatformInt64 randomDay,
        required bool useElevation,
        required ZmanimPreset zman}) =>
    RustLib.instance.api.crateApiCalculateZman(
        ateretTorahSunsetOffsetMinutes: ateretTorahSunsetOffsetMinutes,
        candleLightingOffsetMinutes: candleLightingOffsetMinutes,
        useAstronomicalChatzosForOtherZmanim:
            useAstronomicalChatzosForOtherZmanim,
        latitude: latitude,
        longitude: longitude,
        elevation: elevation,
        timezone: timezone,
        randomYear: randomYear,
        randomMonth: randomMonth,
        randomDay: randomDay,
        useElevation: useElevation,
        zman: zman);

/// Get all the ZmanimPresets supported by the library
List<ZmanimPreset> presets() => RustLib.instance.api.crateApiPresets();

(int, int, int)? jewishDateToGregorianDate(
        {required int year, required int month, required int day}) =>
    RustLib.instance.api
        .crateApiJewishDateToGregorianDate(year: year, month: month, day: day);

(int, int, int)? gregorianDateToJewishDate(
        {required int year, required int month, required int day}) =>
    RustLib.instance.api
        .crateApiGregorianDateToJewishDate(year: year, month: month, day: day);

(int, int, int)? addDaysToJewishDate(
        {required int year,
        required int month,
        required int day,
        required PlatformInt64 daysToAdd}) =>
    RustLib.instance.api.crateApiAddDaysToJewishDate(
        year: year, month: month, day: day, daysToAdd: daysToAdd);

(int, int, int)? addMonthsToJewishDate(
        {required int year,
        required int month,
        required int day,
        required int monthsToAdd}) =>
    RustLib.instance.api.crateApiAddMonthsToJewishDate(
        year: year, month: month, day: day, monthsToAdd: monthsToAdd);

(int, int, int)? addYearsToJewishDate(
        {required int year,
        required int month,
        required int day,
        required int yearsToAdd}) =>
    RustLib.instance.api.crateApiAddYearsToJewishDate(
        year: year, month: month, day: day, yearsToAdd: yearsToAdd);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>
abstract class ZmanimPreset implements RustOpaqueInterface {
  /// Get the name of the ZmanimPreset
  /// This is also the method name in the Java side
  String name();
}
