// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1762524272;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'test_with_java',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateApiZmanimPresetName({required ZmanimPreset that});

  (int, int, int)? crateApiAddDaysToJewishDate(
      {required int year,
      required int month,
      required int day,
      required PlatformInt64 daysToAdd});

  (int, int, int)? crateApiAddMonthsToJewishDate(
      {required int year,
      required int month,
      required int day,
      required int monthsToAdd});

  (int, int, int)? crateApiAddYearsToJewishDate(
      {required int year,
      required int month,
      required int day,
      required int yearsToAdd});

  (String, PlatformInt64)? crateApiCalculateZman(
      {required PlatformInt64 ateretTorahSunsetOffsetMinutes,
      required PlatformInt64 candleLightingOffsetMinutes,
      required bool useAstronomicalChatzosForOtherZmanim,
      required double latitude,
      required double longitude,
      required double elevation,
      required String timezone,
      required PlatformInt64 randomYear,
      required PlatformInt64 randomMonth,
      required PlatformInt64 randomDay,
      required bool useElevation,
      required ZmanimPreset zman});

  String crateApiFindTimezone(
      {required double longitude, required double latitude});

  (int, int, int)? crateApiGregorianDateToJewishDate(
      {required int year, required int month, required int day});

  (int, int, int)? crateApiJewishDateToGregorianDate(
      {required int year, required int month, required int day});

  List<ZmanimPreset> crateApiPresets();

  List<String> crateApiTimezones();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ZmanimPreset;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ZmanimPreset;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ZmanimPresetPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiZmanimPresetName({required ZmanimPreset that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiZmanimPresetNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiZmanimPresetNameConstMeta => const TaskConstMeta(
        debugName: "ZmanimPreset_name",
        argNames: ["that"],
      );

  @override
  (int, int, int)? crateApiAddDaysToJewishDate(
      {required int year,
      required int month,
      required int day,
      required PlatformInt64 daysToAdd}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(year, serializer);
        sse_encode_u_8(month, serializer);
        sse_encode_u_8(day, serializer);
        sse_encode_i_64(daysToAdd, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_i_32_u_8_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAddDaysToJewishDateConstMeta,
      argValues: [year, month, day, daysToAdd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddDaysToJewishDateConstMeta =>
      const TaskConstMeta(
        debugName: "add_days_to_jewish_date",
        argNames: ["year", "month", "day", "daysToAdd"],
      );

  @override
  (int, int, int)? crateApiAddMonthsToJewishDate(
      {required int year,
      required int month,
      required int day,
      required int monthsToAdd}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(year, serializer);
        sse_encode_u_8(month, serializer);
        sse_encode_u_8(day, serializer);
        sse_encode_i_32(monthsToAdd, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_i_32_u_8_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAddMonthsToJewishDateConstMeta,
      argValues: [year, month, day, monthsToAdd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddMonthsToJewishDateConstMeta =>
      const TaskConstMeta(
        debugName: "add_months_to_jewish_date",
        argNames: ["year", "month", "day", "monthsToAdd"],
      );

  @override
  (int, int, int)? crateApiAddYearsToJewishDate(
      {required int year,
      required int month,
      required int day,
      required int yearsToAdd}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(year, serializer);
        sse_encode_u_8(month, serializer);
        sse_encode_u_8(day, serializer);
        sse_encode_i_32(yearsToAdd, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_i_32_u_8_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAddYearsToJewishDateConstMeta,
      argValues: [year, month, day, yearsToAdd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddYearsToJewishDateConstMeta =>
      const TaskConstMeta(
        debugName: "add_years_to_jewish_date",
        argNames: ["year", "month", "day", "yearsToAdd"],
      );

  @override
  (String, PlatformInt64)? crateApiCalculateZman(
      {required PlatformInt64 ateretTorahSunsetOffsetMinutes,
      required PlatformInt64 candleLightingOffsetMinutes,
      required bool useAstronomicalChatzosForOtherZmanim,
      required double latitude,
      required double longitude,
      required double elevation,
      required String timezone,
      required PlatformInt64 randomYear,
      required PlatformInt64 randomMonth,
      required PlatformInt64 randomDay,
      required bool useElevation,
      required ZmanimPreset zman}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(ateretTorahSunsetOffsetMinutes, serializer);
        sse_encode_i_64(candleLightingOffsetMinutes, serializer);
        sse_encode_bool(useAstronomicalChatzosForOtherZmanim, serializer);
        sse_encode_f_64(latitude, serializer);
        sse_encode_f_64(longitude, serializer);
        sse_encode_f_64(elevation, serializer);
        sse_encode_String(timezone, serializer);
        sse_encode_i_64(randomYear, serializer);
        sse_encode_i_64(randomMonth, serializer);
        sse_encode_i_64(randomDay, serializer);
        sse_encode_bool(useElevation, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
            zman, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_string_i_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateZmanConstMeta,
      argValues: [
        ateretTorahSunsetOffsetMinutes,
        candleLightingOffsetMinutes,
        useAstronomicalChatzosForOtherZmanim,
        latitude,
        longitude,
        elevation,
        timezone,
        randomYear,
        randomMonth,
        randomDay,
        useElevation,
        zman
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateZmanConstMeta => const TaskConstMeta(
        debugName: "calculate_zman",
        argNames: [
          "ateretTorahSunsetOffsetMinutes",
          "candleLightingOffsetMinutes",
          "useAstronomicalChatzosForOtherZmanim",
          "latitude",
          "longitude",
          "elevation",
          "timezone",
          "randomYear",
          "randomMonth",
          "randomDay",
          "useElevation",
          "zman"
        ],
      );

  @override
  String crateApiFindTimezone(
      {required double longitude, required double latitude}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(longitude, serializer);
        sse_encode_f_64(latitude, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFindTimezoneConstMeta,
      argValues: [longitude, latitude],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFindTimezoneConstMeta => const TaskConstMeta(
        debugName: "find_timezone",
        argNames: ["longitude", "latitude"],
      );

  @override
  (int, int, int)? crateApiGregorianDateToJewishDate(
      {required int year, required int month, required int day}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(year, serializer);
        sse_encode_u_8(month, serializer);
        sse_encode_u_8(day, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_i_32_u_8_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGregorianDateToJewishDateConstMeta,
      argValues: [year, month, day],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGregorianDateToJewishDateConstMeta =>
      const TaskConstMeta(
        debugName: "gregorian_date_to_jewish_date",
        argNames: ["year", "month", "day"],
      );

  @override
  (int, int, int)? crateApiJewishDateToGregorianDate(
      {required int year, required int month, required int day}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(year, serializer);
        sse_encode_u_8(month, serializer);
        sse_encode_u_8(day, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_i_32_u_8_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiJewishDateToGregorianDateConstMeta,
      argValues: [year, month, day],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiJewishDateToGregorianDateConstMeta =>
      const TaskConstMeta(
        debugName: "jewish_date_to_gregorian_date",
        argNames: ["year", "month", "day"],
      );

  @override
  List<ZmanimPreset> crateApiPresets() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPresetsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPresetsConstMeta => const TaskConstMeta(
        debugName: "presets",
        argNames: [],
      );

  @override
  List<String> crateApiTimezones() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTimezonesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTimezonesConstMeta => const TaskConstMeta(
        debugName: "timezones",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ZmanimPreset => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ZmanimPreset => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset;

  @protected
  ZmanimPreset
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ZmanimPreset
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ZmanimPreset
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  (int, int, int) dco_decode_box_autoadd_record_i_32_u_8_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (int, int, int);
  }

  @protected
  (String, PlatformInt64) dco_decode_box_autoadd_record_string_i_64(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (String, PlatformInt64);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ZmanimPreset>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  (int, int, int)? dco_decode_opt_box_autoadd_record_i_32_u_8_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_record_i_32_u_8_u_8(raw);
  }

  @protected
  (String, PlatformInt64)? dco_decode_opt_box_autoadd_record_string_i_64(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_record_string_i_64(raw);
  }

  @protected
  (int, int, int) dco_decode_record_i_32_u_8_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_i_32(arr[0]),
      dco_decode_u_8(arr[1]),
      dco_decode_u_8(arr[2]),
    );
  }

  @protected
  (String, PlatformInt64) dco_decode_record_string_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_i_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ZmanimPreset
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ZmanimPreset
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ZmanimPreset
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZmanimPresetImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  (int, int, int) sse_decode_box_autoadd_record_i_32_u_8_u_8(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_i_32_u_8_u_8(deserializer));
  }

  @protected
  (String, PlatformInt64) sse_decode_box_autoadd_record_string_i_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_string_i_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ZmanimPreset>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ZmanimPreset>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
          sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
              deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  (int, int, int)? sse_decode_opt_box_autoadd_record_i_32_u_8_u_8(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_i_32_u_8_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, PlatformInt64)? sse_decode_opt_box_autoadd_record_string_i_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_string_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int, int) sse_decode_record_i_32_u_8_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_32(deserializer);
    var var_field1 = sse_decode_u_8(deserializer);
    var var_field2 = sse_decode_u_8(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  (String, PlatformInt64) sse_decode_record_string_i_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_i_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          ZmanimPreset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ZmanimPresetImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          ZmanimPreset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ZmanimPresetImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          ZmanimPreset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ZmanimPresetImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_record_i_32_u_8_u_8(
      (int, int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_i_32_u_8_u_8(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_string_i_64(
      (String, PlatformInt64) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_string_i_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          List<ZmanimPreset> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
          item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_record_i_32_u_8_u_8(
      (int, int, int)? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_i_32_u_8_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_string_i_64(
      (String, PlatformInt64)? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_string_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_i_32_u_8_u_8(
      (int, int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.$1, serializer);
    sse_encode_u_8(self.$2, serializer);
    sse_encode_u_8(self.$3, serializer);
  }

  @protected
  void sse_encode_record_string_i_64(
      (String, PlatformInt64) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_i_64(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ZmanimPresetImpl extends RustOpaque implements ZmanimPreset {
  // Not to be used by end users
  ZmanimPresetImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ZmanimPresetImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ZmanimPreset,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZmanimPreset,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZmanimPresetPtr,
  );

  /// Get the name of the ZmanimPreset
  /// This is also the method name in the Java side
  String name() => RustLib.instance.api.crateApiZmanimPresetName(
        that: this,
      );
}
