// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _AmudResultFfi extends ffi.Struct {
  @ffi.Int32()
  external int tractate;
  @ffi.Uint16()
  external int page;
  @ffi.Int32()
  external int side;
}

final class AmudResult {
  // ignore: public_member_api_docs
  TractateCode tractate;
  // ignore: public_member_api_docs
  int page;
  // ignore: public_member_api_docs
  SideCode side;

  // ignore: public_member_api_docs
  AmudResult({required this.tractate, required this.page, required this.side});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  AmudResult._fromFfi(_AmudResultFfi ffi) :
    tractate = TractateCode.values[ffi.tractate],
    page = ffi.page,
    side = SideCode.values[ffi.side];

  // ignore: unused_element
  _AmudResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_AmudResultFfi>();
    struct.tractate = tractate.index;
    struct.page = page;
    struct.side = side.index;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is AmudResult &&
      other.tractate == tractate &&
      other.page == page &&
      other.side == side;

  @override
  int get hashCode => Object.hashAll([
        tractate,
        page,
        side,
      ]);
}

// dart format on
