// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _CalculatorConfigFfi extends ffi.Struct {
  @ffi.Int32()
  external int candleLightingOffsetMinutes;
  @ffi.Bool()
  external bool useAstronomicalChatzosForOtherZmanim;
  @ffi.Bool()
  external bool useElevation;
  @ffi.Int32()
  external int ateretTorahSunsetOffsetMinutes;
  @ffi.Bool()
  external bool useAstronomicalChatzos;
}

/// Calculator configuration (durations in minutes).
final class CalculatorConfig {
  // ignore: public_member_api_docs
  int candleLightingOffsetMinutes;
  // ignore: public_member_api_docs
  bool useAstronomicalChatzosForOtherZmanim;
  // ignore: public_member_api_docs
  bool useElevation;
  // ignore: public_member_api_docs
  int ateretTorahSunsetOffsetMinutes;
  // ignore: public_member_api_docs
  bool useAstronomicalChatzos;

  // ignore: public_member_api_docs
  CalculatorConfig({required this.candleLightingOffsetMinutes, required this.useAstronomicalChatzosForOtherZmanim, required this.useElevation, required this.ateretTorahSunsetOffsetMinutes, required this.useAstronomicalChatzos});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  CalculatorConfig._fromFfi(_CalculatorConfigFfi ffi) :
    candleLightingOffsetMinutes = ffi.candleLightingOffsetMinutes,
    useAstronomicalChatzosForOtherZmanim = ffi.useAstronomicalChatzosForOtherZmanim,
    useElevation = ffi.useElevation,
    ateretTorahSunsetOffsetMinutes = ffi.ateretTorahSunsetOffsetMinutes,
    useAstronomicalChatzos = ffi.useAstronomicalChatzos;

  // ignore: unused_element
  _CalculatorConfigFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_CalculatorConfigFfi>();
    struct.candleLightingOffsetMinutes = candleLightingOffsetMinutes;
    struct.useAstronomicalChatzosForOtherZmanim = useAstronomicalChatzosForOtherZmanim;
    struct.useElevation = useElevation;
    struct.ateretTorahSunsetOffsetMinutes = ateretTorahSunsetOffsetMinutes;
    struct.useAstronomicalChatzos = useAstronomicalChatzos;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is CalculatorConfig &&
      other.candleLightingOffsetMinutes == candleLightingOffsetMinutes &&
      other.useAstronomicalChatzosForOtherZmanim == useAstronomicalChatzosForOtherZmanim &&
      other.useElevation == useElevation &&
      other.ateretTorahSunsetOffsetMinutes == ateretTorahSunsetOffsetMinutes &&
      other.useAstronomicalChatzos == useAstronomicalChatzos;

  @override
  int get hashCode => Object.hashAll([
        candleLightingOffsetMinutes,
        useAstronomicalChatzosForOtherZmanim,
        useElevation,
        ateretTorahSunsetOffsetMinutes,
        useAstronomicalChatzos,
      ]);
}

// dart format on
