// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Dart entry point: construct once and call instance methods.
final class Calendar implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  Calendar._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('Calendar_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_Calendar_destroy));

  factory Calendar() {
    final result = _Calendar_new();
    return Calendar._fromFfi(result, []);
  }

  HebrewDate? gregorianToHebrew(CivilDate date) {
    final temp = _FinalizedArena();
    final result = _Calendar_gregorian_to_hebrew(_ffi, date._toFfi(temp.arena));
    if (!result.isOk) {
      return null;
    }
    return HebrewDate._fromFfi(result.union.ok);
  }

  CivilDate? hebrewToGregorian(HebrewDate date) {
    final temp = _FinalizedArena();
    final result = _Calendar_hebrew_to_gregorian(_ffi, date._toFfi(temp.arena));
    if (!result.isOk) {
      return null;
    }
    return CivilDate._fromFfi(result.union.ok);
  }

  HolidayList? holidaysOnDate(CivilDate date, bool inIsrael, bool useModernHolidays) {
    final temp = _FinalizedArena();
    final result = _Calendar_holidays_on_date(_ffi, date._toFfi(temp.arena), inIsrael, useModernHolidays);
    return result.address == 0 ? null : HolidayList._fromFfi(result, []);
  }

  bool? isAssurBemelacha(CivilDate date, bool inIsrael) {
    final temp = _FinalizedArena();
    final result = _Calendar_is_assur_bemelacha(_ffi, date._toFfi(temp.arena), inIsrael);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }

  bool? hasCandleLighting(CivilDate date, bool inIsrael) {
    final temp = _FinalizedArena();
    final result = _Calendar_has_candle_lighting(_ffi, date._toFfi(temp.arena), inIsrael);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }

  ParshaCode? todaysParsha(CivilDate date, bool inIsrael) {
    final temp = _FinalizedArena();
    final result = _Calendar_todays_parsha(_ffi, date._toFfi(temp.arena), inIsrael);
    if (!result.isOk) {
      return null;
    }
    return ParshaCode.values[result.union.ok];
  }

  ParshaCode? specialParsha(CivilDate date, bool inIsrael) {
    final temp = _FinalizedArena();
    final result = _Calendar_special_parsha(_ffi, date._toFfi(temp.arena), inIsrael);
    if (!result.isOk) {
      return null;
    }
    return ParshaCode.values[result.union.ok];
  }

  ParshaCode? upcomingParsha(CivilDate date, bool inIsrael) {
    final temp = _FinalizedArena();
    final result = _Calendar_upcoming_parsha(_ffi, date._toFfi(temp.arena), inIsrael);
    if (!result.isOk) {
      return null;
    }
    return ParshaCode.values[result.union.ok];
  }

  int? daysInHebrewYear(int year) {
    final result = _Calendar_days_in_hebrew_year(_ffi, year);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }

  int? daysInHebrewMonth(int year, int month) {
    final result = _Calendar_days_in_hebrew_month(_ffi, year, month);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }

  bool isHebrewLeapYear(int year) {
    final result = _Calendar_is_hebrew_leap_year(_ffi, year);
    return result;
  }

  YearLengthTypeCode? cheshvanKislevKviah(int year) {
    final result = _Calendar_cheshvan_kislev_kviah(_ffi, year);
    if (!result.isOk) {
      return null;
    }
    return YearLengthTypeCode.values[result.union.ok];
  }

}

@_DiplomatFfiUse('Calendar_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'Calendar_destroy')
// ignore: non_constant_identifier_names
external void _Calendar_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('Calendar_new')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'Calendar_new')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _Calendar_new();

@_DiplomatFfiUse('Calendar_gregorian_to_hebrew')
@ffi.Native<_ResultHebrewDateFfiVoid Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi)>(isLeaf: true, symbol: 'Calendar_gregorian_to_hebrew')
// ignore: non_constant_identifier_names
external _ResultHebrewDateFfiVoid _Calendar_gregorian_to_hebrew(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date);

@_DiplomatFfiUse('Calendar_hebrew_to_gregorian')
@ffi.Native<_ResultCivilDateFfiVoid Function(ffi.Pointer<ffi.Opaque>, _HebrewDateFfi)>(isLeaf: true, symbol: 'Calendar_hebrew_to_gregorian')
// ignore: non_constant_identifier_names
external _ResultCivilDateFfiVoid _Calendar_hebrew_to_gregorian(ffi.Pointer<ffi.Opaque> self, _HebrewDateFfi date);

@_DiplomatFfiUse('Calendar_holidays_on_date')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_holidays_on_date')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _Calendar_holidays_on_date(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael, bool useModernHolidays);

@_DiplomatFfiUse('Calendar_is_assur_bemelacha')
@ffi.Native<_ResultBoolVoid Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_is_assur_bemelacha')
// ignore: non_constant_identifier_names
external _ResultBoolVoid _Calendar_is_assur_bemelacha(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael);

@_DiplomatFfiUse('Calendar_has_candle_lighting')
@ffi.Native<_ResultBoolVoid Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_has_candle_lighting')
// ignore: non_constant_identifier_names
external _ResultBoolVoid _Calendar_has_candle_lighting(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael);

@_DiplomatFfiUse('Calendar_todays_parsha')
@ffi.Native<_ResultInt32Void Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_todays_parsha')
// ignore: non_constant_identifier_names
external _ResultInt32Void _Calendar_todays_parsha(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael);

@_DiplomatFfiUse('Calendar_special_parsha')
@ffi.Native<_ResultInt32Void Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_special_parsha')
// ignore: non_constant_identifier_names
external _ResultInt32Void _Calendar_special_parsha(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael);

@_DiplomatFfiUse('Calendar_upcoming_parsha')
@ffi.Native<_ResultInt32Void Function(ffi.Pointer<ffi.Opaque>, _CivilDateFfi, ffi.Bool)>(isLeaf: true, symbol: 'Calendar_upcoming_parsha')
// ignore: non_constant_identifier_names
external _ResultInt32Void _Calendar_upcoming_parsha(ffi.Pointer<ffi.Opaque> self, _CivilDateFfi date, bool inIsrael);

@_DiplomatFfiUse('Calendar_days_in_hebrew_year')
@ffi.Native<_ResultInt32Void Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'Calendar_days_in_hebrew_year')
// ignore: non_constant_identifier_names
external _ResultInt32Void _Calendar_days_in_hebrew_year(ffi.Pointer<ffi.Opaque> self, int year);

@_DiplomatFfiUse('Calendar_days_in_hebrew_month')
@ffi.Native<_ResultUint8Void Function(ffi.Pointer<ffi.Opaque>, ffi.Int32, ffi.Uint8)>(isLeaf: true, symbol: 'Calendar_days_in_hebrew_month')
// ignore: non_constant_identifier_names
external _ResultUint8Void _Calendar_days_in_hebrew_month(ffi.Pointer<ffi.Opaque> self, int year, int month);

@_DiplomatFfiUse('Calendar_is_hebrew_leap_year')
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'Calendar_is_hebrew_leap_year')
// ignore: non_constant_identifier_names
external bool _Calendar_is_hebrew_leap_year(ffi.Pointer<ffi.Opaque> self, int year);

@_DiplomatFfiUse('Calendar_cheshvan_kislev_kviah')
@ffi.Native<_ResultInt32Void Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'Calendar_cheshvan_kislev_kviah')
// ignore: non_constant_identifier_names
external _ResultInt32Void _Calendar_cheshvan_kislev_kviah(ffi.Pointer<ffi.Opaque> self, int year);

// dart format on
