// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _DafResultFfi extends ffi.Struct {
  @ffi.Int32()
  external int tractate;
  @ffi.Uint16()
  external int page;
}

final class DafResult {
  // ignore: public_member_api_docs
  TractateCode tractate;
  // ignore: public_member_api_docs
  int page;

  // ignore: public_member_api_docs
  DafResult({required this.tractate, required this.page});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  DafResult._fromFfi(_DafResultFfi ffi) :
    tractate = TractateCode.values[ffi.tractate],
    page = ffi.page;

  // ignore: unused_element
  _DafResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_DafResultFfi>();
    struct.tractate = tractate.index;
    struct.page = page;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is DafResult &&
      other.tractate == tractate &&
      other.page == page;

  @override
  int get hashCode => Object.hashAll([
        tractate,
        page,
      ]);
}

// dart format on
