// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class FfiLocation implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  FfiLocation._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('FfiLocation_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_FfiLocation_destroy));

  /// Creates a location. Pass an empty timezone string when unknown.
  ///
  /// Throws [ZmanimErrorCode] on failure.
  static FfiLocation new_(double latitude, double longitude, double elevation, String timezoneIana) {
    final temp = _FinalizedArena();
    final result = _FfiLocation_new(latitude, longitude, elevation, timezoneIana._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw ZmanimErrorCode.values[result.union.err];
    }
    return FfiLocation._fromFfi(result.union.ok, []);
  }

}

@_DiplomatFfiUse('FfiLocation_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'FfiLocation_destroy')
// ignore: non_constant_identifier_names
external void _FfiLocation_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('FfiLocation_new')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Double, ffi.Double, ffi.Double, _SliceUtf8)>(isLeaf: true, symbol: 'FfiLocation_new')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _FfiLocation_new(double latitude, double longitude, double elevation, _SliceUtf8 timezoneIana);

// dart format on
