// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class FfiZmanimCalculator implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  FfiZmanimCalculator._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('FfiZmanimCalculator_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_FfiZmanimCalculator_destroy));

  static FfiZmanimCalculator? new_(FfiLocation location, int year, int month, int day, CalculatorConfig config) {
    final temp = _FinalizedArena();
    final result = _FfiZmanimCalculator_new(location._ffi, year, month, day, config._toFfi(temp.arena));
    return result.address == 0 ? null : FfiZmanimCalculator._fromFfi(result, []);
  }

  /// Calculates a zman preset by index, returning UTC epoch milliseconds.
  ///
  /// The index matches [ZmanPresetId] in the generated [crate::zman_preset] module.
  ///
  /// Throws [ZmanimErrorCode] on failure.
  int calculateZmanByIndex(int presetIndex) {
    final result = _FfiZmanimCalculator_calculate_zman_by_index(_ffi, presetIndex);
    if (!result.isOk) {
      throw ZmanimErrorCode.values[result.union.err];
    }
    return result.union.ok;
  }

}

@_DiplomatFfiUse('FfiZmanimCalculator_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'FfiZmanimCalculator_destroy')
// ignore: non_constant_identifier_names
external void _FfiZmanimCalculator_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('FfiZmanimCalculator_new')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>, ffi.Int32, ffi.Uint8, ffi.Uint8, _CalculatorConfigFfi)>(isLeaf: true, symbol: 'FfiZmanimCalculator_new')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _FfiZmanimCalculator_new(ffi.Pointer<ffi.Opaque> location, int year, int month, int day, _CalculatorConfigFfi config);

@_DiplomatFfiUse('FfiZmanimCalculator_calculate_zman_by_index')
@ffi.Native<_ResultInt64Int32 Function(ffi.Pointer<ffi.Opaque>, ffi.Uint32)>(isLeaf: true, symbol: 'FfiZmanimCalculator_calculate_zman_by_index')
// ignore: non_constant_identifier_names
external _ResultInt64Int32 _FfiZmanimCalculator_calculate_zman_by_index(ffi.Pointer<ffi.Opaque> self, int presetIndex);

// dart format on
