// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _HebrewDateFfi extends ffi.Struct {
  @ffi.Int32()
  external int year;
  @ffi.Uint8()
  external int month;
  @ffi.Uint8()
  external int day;
}

/// Hebrew calendar date (year, month code, day).
final class HebrewDate {
  // ignore: public_member_api_docs
  int year;
  // ignore: public_member_api_docs
  int month;
  // ignore: public_member_api_docs
  int day;

  // ignore: public_member_api_docs
  HebrewDate({required this.year, required this.month, required this.day});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  HebrewDate._fromFfi(_HebrewDateFfi ffi) :
    year = ffi.year,
    month = ffi.month,
    day = ffi.day;

  // ignore: unused_element
  _HebrewDateFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_HebrewDateFfi>();
    struct.year = year;
    struct.month = month;
    struct.day = day;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is HebrewDate &&
      other.year == year &&
      other.month == month &&
      other.day == day;

  @override
  int get hashCode => Object.hashAll([
        year,
        month,
        day,
      ]);
}

// dart format on
