// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum HolidayCode {
  // ignore: public_member_api_docs
  erevPesach,
  // ignore: public_member_api_docs
  pesach,
  // ignore: public_member_api_docs
  cholHamoedPesach,
  // ignore: public_member_api_docs
  pesachSheni,
  // ignore: public_member_api_docs
  erevShavuos,
  // ignore: public_member_api_docs
  shavuos,
  // ignore: public_member_api_docs
  seventeenthOfTammuz,
  // ignore: public_member_api_docs
  tishahBav,
  // ignore: public_member_api_docs
  tuBav,
  // ignore: public_member_api_docs
  erevRoshHashana,
  // ignore: public_member_api_docs
  roshHashana,
  // ignore: public_member_api_docs
  fastOfGedalyah,
  // ignore: public_member_api_docs
  erevYomKippur,
  // ignore: public_member_api_docs
  yomKippur,
  // ignore: public_member_api_docs
  erevSuccos,
  // ignore: public_member_api_docs
  succos,
  // ignore: public_member_api_docs
  cholHamoedSuccos,
  // ignore: public_member_api_docs
  hoshanaRabbah,
  // ignore: public_member_api_docs
  sheminiAtzeres,
  // ignore: public_member_api_docs
  simchasTorah,
  // ignore: public_member_api_docs
  chanukah,
  // ignore: public_member_api_docs
  tenthOfTeves,
  // ignore: public_member_api_docs
  tuBshvat,
  // ignore: public_member_api_docs
  fastOfEsther,
  // ignore: public_member_api_docs
  purim,
  // ignore: public_member_api_docs
  shushanPurim,
  // ignore: public_member_api_docs
  purimKatan,
  // ignore: public_member_api_docs
  roshChodesh,
  // ignore: public_member_api_docs
  yomHaShoah,
  // ignore: public_member_api_docs
  yomHazikaron,
  // ignore: public_member_api_docs
  yomHaatzmaut,
  // ignore: public_member_api_docs
  yomYerushalayim,
  // ignore: public_member_api_docs
  lagBomer,
  // ignore: public_member_api_docs
  shushanPurimKatan,
  // ignore: public_member_api_docs
  isruChag,
  // ignore: public_member_api_docs
  yomKippurKatan,
  // ignore: public_member_api_docs
  behab,
  // ignore: public_member_api_docs
  fastOfTheFirstborn,
  // ignore: public_member_api_docs
  countOfTheOmer,
  // ignore: public_member_api_docs
  birchasHachamah,
  // ignore: public_member_api_docs
  macharHachodesh,
  // ignore: public_member_api_docs
  shabbosMevarchim;

}

// dart format on
