// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _HolidayEntryFfi extends ffi.Struct {
  @ffi.Int32()
  external int code;
  @ffi.Uint8()
  external int subDay;
}

/// A holiday occurring on a date, with an optional sub-day (Chanukah, Omer).
final class HolidayEntry {
  // ignore: public_member_api_docs
  HolidayCode code;
  // ignore: public_member_api_docs
  int subDay;

  // ignore: public_member_api_docs
  HolidayEntry({required this.code, required this.subDay});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  HolidayEntry._fromFfi(_HolidayEntryFfi ffi) :
    code = HolidayCode.values[ffi.code],
    subDay = ffi.subDay;

  // ignore: unused_element
  _HolidayEntryFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_HolidayEntryFfi>();
    struct.code = code.index;
    struct.subDay = subDay;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is HolidayEntry &&
      other.code == code &&
      other.subDay == subDay;

  @override
  int get hashCode => Object.hashAll([
        code,
        subDay,
      ]);
}

// dart format on
