// generated by diplomat-tool
// dart format off

import 'dart:convert';
// ignore: unused_import
import 'dart:core' as core;
// ignore: unused_shown_name
import 'dart:core' show Object, String, bool, double, int, override;
import 'dart:ffi' as ffi;
// ignore: unused_import
import 'dart:typed_data';
import 'package:ffi/ffi.dart' as ffi2 show Arena, calloc;
import 'package:meta/meta.dart' as meta;
part 'AmudResult.g.dart';
part 'CalculatorConfig.g.dart';
part 'Calendar.g.dart';
part 'CivilDate.g.dart';
part 'DafResult.g.dart';
part 'FfiLocation.g.dart';
part 'FfiZmanimCalculator.g.dart';
part 'HebrewDate.g.dart';
part 'HolidayCode.g.dart';
part 'HolidayEntry.g.dart';
part 'HolidayList.g.dart';
part 'Limudim.g.dart';
part 'MishnaResult.g.dart';
part 'MishnasResult.g.dart';
part 'ParshaCode.g.dart';
part 'PirkeiAvosResult.g.dart';
part 'SideCode.g.dart';
part 'TehillimResult.g.dart';
part 'TractateCode.g.dart';
part 'YearLengthTypeCode.g.dart';
part 'ZmanPresetId.g.dart';
part 'ZmanPresets.g.dart';
part 'ZmanimErrorCode.g.dart';

// ignore: experimental_member_use
@meta.RecordUse()
final class _DiplomatFfiUse {
  final String symbol;

  // ignore: experimental_member_use
  const _DiplomatFfiUse(@meta.mustBeConst this.symbol);
}

/// A [Rune] is a Unicode code point, such as `a`, or `💡`.
///
/// The recommended way to obtain a [Rune] is to create it from a
/// [String], which is conceptually a sequence of [Rune]s. For
/// example, `'a'.runes.first` is equal to the [Rune] `a`.
///
/// Dart does not have a character/rune literal (https://github.com/dart-lang/language/issues/886),
/// so integer literals need to be used. For example the Unicode code point
/// U+1F4A1, `💡`, can be represented by `0x1F4A1`.
///
/// A [String] can be constructed from a [Rune] using (the [confusingly named](
/// https://github.com/dart-lang/sdk/issues/56304)) [String.fromCharCode].
typedef Rune = int;

// ignore: unused_element
final _callocFree = core.Finalizer(ffi2.calloc.free);

// ignore: unused_element
final _nopFree = core.Finalizer((nothing) => {});

// ignore: unused_element
final _rustFree = core.Finalizer(
  (({ffi.Pointer<ffi.Void> pointer, int bytes, int align}) record) =>
      _diplomat_free(record.pointer, record.bytes, record.align),
);

// ignore: unused_element
final class _RustAlloc implements ffi.Allocator {
  @override
  ffi.Pointer<T> allocate<T extends ffi.NativeType>(
    int byteCount, {
    int? alignment,
  }) {
    return _diplomat_alloc(byteCount, alignment ?? 1).cast();
  }

  @override
  void free(ffi.Pointer<ffi.NativeType> pointer) {
    throw 'Internal error: should not deallocate in Rust memory';
  }
}

@_DiplomatFfiUse('diplomat_alloc')
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>(
  symbol: 'diplomat_alloc',
  isLeaf: true,
)
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Void> _diplomat_alloc(int len, int align);

@_DiplomatFfiUse('diplomat_free')
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Void>, ffi.Size, ffi.Size)>(
  symbol: 'diplomat_free',
  isLeaf: true,
)
// ignore: non_constant_identifier_names
external int _diplomat_free(ffi.Pointer<ffi.Void> ptr, int len, int align);

// ignore: unused_element
class _FinalizedArena {
  final ffi2.Arena arena;
  static final core.Finalizer<ffi2.Arena> _finalizer = core.Finalizer(
    (arena) => arena.releaseAll(),
  );

  // ignore: unused_element
  _FinalizedArena() : arena = ffi2.Arena() {
    _finalizer.attach(this, arena);
  }

  // ignore: unused_element
  _FinalizedArena.withLifetime(core.List<core.List<Object>> lifetimeAppendArray)
    : arena = ffi2.Arena() {
    _finalizer.attach(this, arena);
    for (final edge in lifetimeAppendArray) {
      edge.add(this);
    }
  }
}

final class _ResultAmudResultFfiVoidUnion extends ffi.Union {
  external _AmudResultFfi ok;

}

final class _ResultAmudResultFfiVoid extends ffi.Struct {
  external _ResultAmudResultFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultAmudResultFfiVoid.ok(_AmudResultFfi val) {
    final struct = ffi.Struct.create<_ResultAmudResultFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultAmudResultFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultAmudResultFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultBoolVoidUnion extends ffi.Union {
  @ffi.Bool()
  external bool ok;

}

final class _ResultBoolVoid extends ffi.Struct {
  external _ResultBoolVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultBoolVoid.ok(bool val) {
    final struct = ffi.Struct.create<_ResultBoolVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultBoolVoid.err() {
    final struct = ffi.Struct.create<_ResultBoolVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultCivilDateFfiVoidUnion extends ffi.Union {
  external _CivilDateFfi ok;

}

final class _ResultCivilDateFfiVoid extends ffi.Struct {
  external _ResultCivilDateFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultCivilDateFfiVoid.ok(_CivilDateFfi val) {
    final struct = ffi.Struct.create<_ResultCivilDateFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultCivilDateFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultCivilDateFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultDafResultFfiVoidUnion extends ffi.Union {
  external _DafResultFfi ok;

}

final class _ResultDafResultFfiVoid extends ffi.Struct {
  external _ResultDafResultFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultDafResultFfiVoid.ok(_DafResultFfi val) {
    final struct = ffi.Struct.create<_ResultDafResultFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultDafResultFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultDafResultFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultHebrewDateFfiVoidUnion extends ffi.Union {
  external _HebrewDateFfi ok;

}

final class _ResultHebrewDateFfiVoid extends ffi.Struct {
  external _ResultHebrewDateFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultHebrewDateFfiVoid.ok(_HebrewDateFfi val) {
    final struct = ffi.Struct.create<_ResultHebrewDateFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultHebrewDateFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultHebrewDateFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultHolidayEntryFfiVoidUnion extends ffi.Union {
  external _HolidayEntryFfi ok;

}

final class _ResultHolidayEntryFfiVoid extends ffi.Struct {
  external _ResultHolidayEntryFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultHolidayEntryFfiVoid.ok(_HolidayEntryFfi val) {
    final struct = ffi.Struct.create<_ResultHolidayEntryFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultHolidayEntryFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultHolidayEntryFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultInt32VoidUnion extends ffi.Union {
  @ffi.Int32()
  external int ok;

}

final class _ResultInt32Void extends ffi.Struct {
  external _ResultInt32VoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultInt32Void.ok(int val) {
    final struct = ffi.Struct.create<_ResultInt32Void>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultInt32Void.err() {
    final struct = ffi.Struct.create<_ResultInt32Void>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultInt64Int32Union extends ffi.Union {
  @ffi.Int64()
  external int ok;

  @ffi.Int32()
  external int err;
}

final class _ResultInt64Int32 extends ffi.Struct {
  external _ResultInt64Int32Union union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultInt64Int32.ok(int val) {
    final struct = ffi.Struct.create<_ResultInt64Int32>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultInt64Int32.err(int val) {
    final struct = ffi.Struct.create<_ResultInt64Int32>();
    struct.isOk = false;
    struct.union.err = val;
    return struct;
  }
}

final class _ResultMishnasResultFfiVoidUnion extends ffi.Union {
  external _MishnasResultFfi ok;

}

final class _ResultMishnasResultFfiVoid extends ffi.Struct {
  external _ResultMishnasResultFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultMishnasResultFfiVoid.ok(_MishnasResultFfi val) {
    final struct = ffi.Struct.create<_ResultMishnasResultFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultMishnasResultFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultMishnasResultFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultOpaqueInt32Union extends ffi.Union {
  external ffi.Pointer<ffi.Opaque> ok;

  @ffi.Int32()
  external int err;
}

final class _ResultOpaqueInt32 extends ffi.Struct {
  external _ResultOpaqueInt32Union union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultOpaqueInt32.ok(ffi.Pointer<ffi.Opaque> val) {
    final struct = ffi.Struct.create<_ResultOpaqueInt32>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultOpaqueInt32.err(int val) {
    final struct = ffi.Struct.create<_ResultOpaqueInt32>();
    struct.isOk = false;
    struct.union.err = val;
    return struct;
  }
}

final class _ResultPirkeiAvosResultFfiVoidUnion extends ffi.Union {
  external _PirkeiAvosResultFfi ok;

}

final class _ResultPirkeiAvosResultFfiVoid extends ffi.Struct {
  external _ResultPirkeiAvosResultFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultPirkeiAvosResultFfiVoid.ok(_PirkeiAvosResultFfi val) {
    final struct = ffi.Struct.create<_ResultPirkeiAvosResultFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultPirkeiAvosResultFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultPirkeiAvosResultFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultTehillimResultFfiVoidUnion extends ffi.Union {
  external _TehillimResultFfi ok;

}

final class _ResultTehillimResultFfiVoid extends ffi.Struct {
  external _ResultTehillimResultFfiVoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultTehillimResultFfiVoid.ok(_TehillimResultFfi val) {
    final struct = ffi.Struct.create<_ResultTehillimResultFfiVoid>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultTehillimResultFfiVoid.err() {
    final struct = ffi.Struct.create<_ResultTehillimResultFfiVoid>();
    struct.isOk = false;
    return struct;
  }
}

final class _ResultUint8VoidUnion extends ffi.Union {
  @ffi.Uint8()
  external int ok;

}

final class _ResultUint8Void extends ffi.Struct {
  external _ResultUint8VoidUnion union;

  @ffi.Bool()
  external bool isOk;

  // ignore: unused_element
  factory _ResultUint8Void.ok(int val) {
    final struct = ffi.Struct.create<_ResultUint8Void>();
    struct.isOk = true;
    struct.union.ok = val;
    return struct;
  }
  // ignore: unused_element
  factory _ResultUint8Void.err() {
    final struct = ffi.Struct.create<_ResultUint8Void>();
    struct.isOk = false;
    return struct;
  }
}

final class _SliceUtf8 extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> _data;

  @ffi.Size()
  external int _length;

  // This is expensive
  @override
  bool operator ==(Object other) {
    if (other is! _SliceUtf8 || other._length != _length) {
      return false;
    }

    for (var i = 0; i < _length; i++) {
      if (other._data[i] != _data[i]) {
        return false;
      }
    }
    return true;
  }

  // This is cheap
  @override
  int get hashCode => _length.hashCode;

  // ignore: unused_element
  String _toDart(core.List<Object> lifetimeEdges, {bool isStatic = false}) {
    final r = const Utf8Decoder().convert(_data.asTypedList(_length));
    if (lifetimeEdges.isEmpty && !isStatic) {
      _diplomat_free(_data.cast(), _length, 1);
    } else {
      // Lifetime edges will be cleaned up
    }
    return r;
  }
}

extension on String {
  // ignore: unused_element
  _SliceUtf8 _utf8AllocIn(ffi.Allocator alloc) {
    final slice = ffi.Struct.create<_SliceUtf8>();
    final encoded = const Utf8Encoder().convert(this);
    slice._data = alloc(encoded.length)..asTypedList(encoded.length).setRange(0, encoded.length, encoded);
    slice._length = encoded.length;
    return slice;
  }
}

// dart format on
