// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _MishnaResultFfi extends ffi.Struct {
  @ffi.Int32()
  external int tractate;
  @ffi.Size()
  external int chapter;
  @ffi.Uint16()
  external int mishna;
}

final class MishnaResult {
  // ignore: public_member_api_docs
  TractateCode tractate;
  // ignore: public_member_api_docs
  int chapter;
  // ignore: public_member_api_docs
  int mishna;

  // ignore: public_member_api_docs
  MishnaResult({required this.tractate, required this.chapter, required this.mishna});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  MishnaResult._fromFfi(_MishnaResultFfi ffi) :
    tractate = TractateCode.values[ffi.tractate],
    chapter = ffi.chapter,
    mishna = ffi.mishna;

  // ignore: unused_element
  _MishnaResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_MishnaResultFfi>();
    struct.tractate = tractate.index;
    struct.chapter = chapter;
    struct.mishna = mishna;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is MishnaResult &&
      other.tractate == tractate &&
      other.chapter == chapter &&
      other.mishna == mishna;

  @override
  int get hashCode => Object.hashAll([
        tractate,
        chapter,
        mishna,
      ]);
}

// dart format on
