// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _MishnasResultFfi extends ffi.Struct {
  external _MishnaResultFfi start;
  external _MishnaResultFfi end;
}

final class MishnasResult {
  // ignore: public_member_api_docs
  MishnaResult start;
  // ignore: public_member_api_docs
  MishnaResult end;

  // ignore: public_member_api_docs
  MishnasResult({required this.start, required this.end});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  MishnasResult._fromFfi(_MishnasResultFfi ffi) :
    start = MishnaResult._fromFfi(ffi.start),
    end = MishnaResult._fromFfi(ffi.end);

  // ignore: unused_element
  _MishnasResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_MishnasResultFfi>();
    struct.start = start._toFfi(temp);
    struct.end = end._toFfi(temp);
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is MishnasResult &&
      other.start == start &&
      other.end == end;

  @override
  int get hashCode => Object.hashAll([
        start,
        end,
      ]);
}

// dart format on
