// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _PirkeiAvosResultFfi extends ffi.Struct {
  @ffi.Uint8()
  external int kind;
  @ffi.Uint8()
  external int perek1;
  @ffi.Uint8()
  external int perek2;
}

/// Flat tagged union for Pirkei Avos (`kind`: 0 = single, 1 = combined).
final class PirkeiAvosResult {
  // ignore: public_member_api_docs
  int kind;
  // ignore: public_member_api_docs
  int perek1;
  // ignore: public_member_api_docs
  int perek2;

  // ignore: public_member_api_docs
  PirkeiAvosResult({required this.kind, required this.perek1, required this.perek2});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  PirkeiAvosResult._fromFfi(_PirkeiAvosResultFfi ffi) :
    kind = ffi.kind,
    perek1 = ffi.perek1,
    perek2 = ffi.perek2;

  // ignore: unused_element
  _PirkeiAvosResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_PirkeiAvosResultFfi>();
    struct.kind = kind;
    struct.perek1 = perek1;
    struct.perek2 = perek2;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is PirkeiAvosResult &&
      other.kind == kind &&
      other.perek1 == perek1 &&
      other.perek2 == perek2;

  @override
  int get hashCode => Object.hashAll([
        kind,
        perek1,
        perek2,
      ]);
}

// dart format on
