// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _TehillimResultFfi extends ffi.Struct {
  @ffi.Uint8()
  external int kind;
  @ffi.Uint8()
  external int start;
  @ffi.Uint8()
  external int end;
  @ffi.Uint8()
  external int psalm;
  @ffi.Uint16()
  external int startVerse;
  @ffi.Uint16()
  external int endVerse;
}

/// Flat tagged union for Tehillim (`kind`: 0 = psalms range, 1 = verse range).
final class TehillimResult {
  // ignore: public_member_api_docs
  int kind;
  // ignore: public_member_api_docs
  int start;
  // ignore: public_member_api_docs
  int end;
  // ignore: public_member_api_docs
  int psalm;
  // ignore: public_member_api_docs
  int startVerse;
  // ignore: public_member_api_docs
  int endVerse;

  // ignore: public_member_api_docs
  TehillimResult({required this.kind, required this.start, required this.end, required this.psalm, required this.startVerse, required this.endVerse});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  TehillimResult._fromFfi(_TehillimResultFfi ffi) :
    kind = ffi.kind,
    start = ffi.start,
    end = ffi.end,
    psalm = ffi.psalm,
    startVerse = ffi.startVerse,
    endVerse = ffi.endVerse;

  // ignore: unused_element
  _TehillimResultFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_TehillimResultFfi>();
    struct.kind = kind;
    struct.start = start;
    struct.end = end;
    struct.psalm = psalm;
    struct.startVerse = startVerse;
    struct.endVerse = endVerse;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is TehillimResult &&
      other.kind == kind &&
      other.start == start &&
      other.end == end &&
      other.psalm == psalm &&
      other.startVerse == startVerse &&
      other.endVerse == endVerse;

  @override
  int get hashCode => Object.hashAll([
        kind,
        start,
        end,
        psalm,
        startVerse,
        endVerse,
      ]);
}

// dart format on
