// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum TractateCode {
  // ignore: public_member_api_docs
  berachos,
  // ignore: public_member_api_docs
  peah,
  // ignore: public_member_api_docs
  demai,
  // ignore: public_member_api_docs
  kilayim,
  // ignore: public_member_api_docs
  sheviis,
  // ignore: public_member_api_docs
  terumos,
  // ignore: public_member_api_docs
  maasros,
  // ignore: public_member_api_docs
  maaserSheni,
  // ignore: public_member_api_docs
  chalah,
  // ignore: public_member_api_docs
  orlah,
  // ignore: public_member_api_docs
  bikurim,
  // ignore: public_member_api_docs
  shabbos,
  // ignore: public_member_api_docs
  eruvin,
  // ignore: public_member_api_docs
  pesachim,
  // ignore: public_member_api_docs
  shekalim,
  // ignore: public_member_api_docs
  yoma,
  // ignore: public_member_api_docs
  sukkah,
  // ignore: public_member_api_docs
  beitzah,
  // ignore: public_member_api_docs
  roshHashanah,
  // ignore: public_member_api_docs
  taanis,
  // ignore: public_member_api_docs
  megillah,
  // ignore: public_member_api_docs
  moedKatan,
  // ignore: public_member_api_docs
  chagigah,
  // ignore: public_member_api_docs
  yevamos,
  // ignore: public_member_api_docs
  kesubos,
  // ignore: public_member_api_docs
  nedarim,
  // ignore: public_member_api_docs
  nazir,
  // ignore: public_member_api_docs
  sotah,
  // ignore: public_member_api_docs
  gitin,
  // ignore: public_member_api_docs
  kiddushin,
  // ignore: public_member_api_docs
  bavaKamma,
  // ignore: public_member_api_docs
  bavaMetzia,
  // ignore: public_member_api_docs
  bavaBasra,
  // ignore: public_member_api_docs
  sanhedrin,
  // ignore: public_member_api_docs
  makkos,
  // ignore: public_member_api_docs
  shevuos,
  // ignore: public_member_api_docs
  eduyos,
  // ignore: public_member_api_docs
  avodahZarah,
  // ignore: public_member_api_docs
  avos,
  // ignore: public_member_api_docs
  horiyos,
  // ignore: public_member_api_docs
  zevachim,
  // ignore: public_member_api_docs
  menachos,
  // ignore: public_member_api_docs
  chullin,
  // ignore: public_member_api_docs
  bechoros,
  // ignore: public_member_api_docs
  arachin,
  // ignore: public_member_api_docs
  temurah,
  // ignore: public_member_api_docs
  kerisos,
  // ignore: public_member_api_docs
  meilah,
  // ignore: public_member_api_docs
  tamid,
  // ignore: public_member_api_docs
  midos,
  // ignore: public_member_api_docs
  kinnim,
  // ignore: public_member_api_docs
  keilim,
  // ignore: public_member_api_docs
  ohalos,
  // ignore: public_member_api_docs
  negaim,
  // ignore: public_member_api_docs
  parah,
  // ignore: public_member_api_docs
  taharos,
  // ignore: public_member_api_docs
  mikvaos,
  // ignore: public_member_api_docs
  niddah,
  // ignore: public_member_api_docs
  machshirin,
  // ignore: public_member_api_docs
  zavim,
  // ignore: public_member_api_docs
  tevulYom,
  // ignore: public_member_api_docs
  yadayim,
  // ignore: public_member_api_docs
  uktzin;

}

// dart format on
