// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum YearLengthTypeCode {
  // ignore: public_member_api_docs
  chaserim,
  // ignore: public_member_api_docs
  kesidran,
  // ignore: public_member_api_docs
  shelaimim;

}

// dart format on
