// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Dart entry point: construct once and call instance methods.
final class ZmanPresets implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  ZmanPresets._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('ZmanPresets_destroy')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_ZmanPresets_destroy));

  factory ZmanPresets() {
    final result = _ZmanPresets_new();
    return ZmanPresets._fromFfi(result, []);
  }

  int presetCount() {
    final result = _ZmanPresets_preset_count(_ffi);
    return result;
  }

  bool presetName(ZmanPresetId preset) {
    final result = _ZmanPresets_preset_name(_ffi, preset.index);
    return result;
  }

  bool presetDeprecated(ZmanPresetId preset) {
    final result = _ZmanPresets_preset_deprecated(_ffi, preset.index);
    return result;
  }

  bool presetMethodName(ZmanPresetId preset) {
    final result = _ZmanPresets_preset_method_name(_ffi, preset.index);
    return result;
  }

}

@_DiplomatFfiUse('ZmanPresets_destroy')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'ZmanPresets_destroy')
// ignore: non_constant_identifier_names
external void _ZmanPresets_destroy(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('ZmanPresets_new')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'ZmanPresets_new')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _ZmanPresets_new();

@_DiplomatFfiUse('ZmanPresets_preset_count')
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'ZmanPresets_preset_count')
// ignore: non_constant_identifier_names
external int _ZmanPresets_preset_count(ffi.Pointer<ffi.Opaque> self);

@_DiplomatFfiUse('ZmanPresets_preset_name')
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'ZmanPresets_preset_name')
// ignore: non_constant_identifier_names
external bool _ZmanPresets_preset_name(ffi.Pointer<ffi.Opaque> self, int preset);

@_DiplomatFfiUse('ZmanPresets_preset_deprecated')
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'ZmanPresets_preset_deprecated')
// ignore: non_constant_identifier_names
external bool _ZmanPresets_preset_deprecated(ffi.Pointer<ffi.Opaque> self, int preset);

@_DiplomatFfiUse('ZmanPresets_preset_method_name')
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Opaque>, ffi.Int32)>(isLeaf: true, symbol: 'ZmanPresets_preset_method_name')
// ignore: non_constant_identifier_names
external bool _ZmanPresets_preset_method_name(ffi.Pointer<ffi.Opaque> self, int preset);

// dart format on
