// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum ZmanimErrorCode {
  // ignore: public_member_api_docs
  invalidLatitude,
  // ignore: public_member_api_docs
  invalidLongitude,
  // ignore: public_member_api_docs
  invalidElevation,
  // ignore: public_member_api_docs
  timeZoneRequired,
  // ignore: public_member_api_docs
  calculationError,
  // ignore: public_member_api_docs
  allDay,
  // ignore: public_member_api_docs
  allNight,
  // ignore: public_member_api_docs
  timeConversionError,
  // ignore: public_member_api_docs
  invalidForDate,
  // ignore: public_member_api_docs
  invalidHours;

}

// dart format on
