// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Stable identifier for a generated zman preset.
enum ZmanPresetId {
  // ignore: public_member_api_docs
  alos120Minutes,
  // ignore: public_member_api_docs
  alos120Zmanis,
  // ignore: public_member_api_docs
  alos16Point1Degrees,
  // ignore: public_member_api_docs
  alos18Degrees,
  // ignore: public_member_api_docs
  alos19Degrees,
  // ignore: public_member_api_docs
  alos19Point8Degrees,
  // ignore: public_member_api_docs
  alos26Degrees,
  // ignore: public_member_api_docs
  alos60Minutes,
  // ignore: public_member_api_docs
  alos72Minutes,
  // ignore: public_member_api_docs
  alos72Zmanis,
  // ignore: public_member_api_docs
  alos90Minutes,
  // ignore: public_member_api_docs
  alos90Zmanis,
  // ignore: public_member_api_docs
  alos96Minutes,
  // ignore: public_member_api_docs
  alos96Zmanis,
  // ignore: public_member_api_docs
  alosBaalHatanya,
  // ignore: public_member_api_docs
  bainHashmashosRt13Point24Degrees,
  // ignore: public_member_api_docs
  bainHashmashosRt13Point5MinutesBefore7Point083Degrees,
  // ignore: public_member_api_docs
  bainHashmashosRt2Stars,
  // ignore: public_member_api_docs
  bainHashmashosRt58Point5Minutes,
  // ignore: public_member_api_docs
  bainHashmashosYereim13Point5Minutes,
  // ignore: public_member_api_docs
  bainHashmashosYereim16Point875Minutes,
  // ignore: public_member_api_docs
  bainHashmashosYereim18Minutes,
  // ignore: public_member_api_docs
  bainHashmashosYereim2Point1Degrees,
  // ignore: public_member_api_docs
  bainHashmashosYereim2Point8Degrees,
  // ignore: public_member_api_docs
  bainHashmashosYereim3Point05Degrees,
  // ignore: public_member_api_docs
  beginAstronomicalTwilight,
  // ignore: public_member_api_docs
  beginCivilTwilight,
  // ignore: public_member_api_docs
  beginNauticalTwilight,
  // ignore: public_member_api_docs
  candleLighting,
  // ignore: public_member_api_docs
  chatzosHalayla,
  // ignore: public_member_api_docs
  chatzosHayom,
  // ignore: public_member_api_docs
  chatzosHayomAsHalfDay,
  // ignore: public_member_api_docs
  elevationAdjustedSunrise,
  // ignore: public_member_api_docs
  elevationAdjustedSunset,
  // ignore: public_member_api_docs
  endAstronomicalTwilight,
  // ignore: public_member_api_docs
  endCivilTwilight,
  // ignore: public_member_api_docs
  endNauticalTwilight,
  // ignore: public_member_api_docs
  fixedLocalChatzosHayom,
  // ignore: public_member_api_docs
  minchaGedola16Point1Degrees,
  // ignore: public_member_api_docs
  minchaGedola30Minutes,
  // ignore: public_member_api_docs
  minchaGedola72Minutes,
  // ignore: public_member_api_docs
  minchaGedolaAhavatShalom,
  // ignore: public_member_api_docs
  minchaGedolaAteretTorah,
  // ignore: public_member_api_docs
  minchaGedolaBaalHatanya,
  // ignore: public_member_api_docs
  minchaGedolaGra,
  // ignore: public_member_api_docs
  minchaGedolaGrafixedLocalChatzos30Minutes,
  // ignore: public_member_api_docs
  minchaGedolaGragreaterThan30,
  // ignore: public_member_api_docs
  minchaKetana16Point1Degrees,
  // ignore: public_member_api_docs
  minchaKetana72Minutes,
  // ignore: public_member_api_docs
  minchaKetanaAhavatShalom,
  // ignore: public_member_api_docs
  minchaKetanaAteretTorah,
  // ignore: public_member_api_docs
  minchaKetanaBaalHatanya,
  // ignore: public_member_api_docs
  minchaKetanaGra,
  // ignore: public_member_api_docs
  minchaKetanaGrafixedLocalChatzosToSunset,
  // ignore: public_member_api_docs
  misheyakir10Point2Degrees,
  // ignore: public_member_api_docs
  misheyakir11Degrees,
  // ignore: public_member_api_docs
  misheyakir11Point5Degrees,
  // ignore: public_member_api_docs
  misheyakir12Point85Degrees,
  // ignore: public_member_api_docs
  misheyakir7Point65Degrees,
  // ignore: public_member_api_docs
  misheyakir9Point5Degrees,
  // ignore: public_member_api_docs
  plagAhavatShalom,
  // ignore: public_member_api_docs
  plagAlos16Point1DegreesToTzaisGeonim7Point083Degrees,
  // ignore: public_member_api_docs
  plagAlosToSunset,
  // ignore: public_member_api_docs
  plagHamincha120Minutes,
  // ignore: public_member_api_docs
  plagHamincha120MinutesZmanis,
  // ignore: public_member_api_docs
  plagHamincha16Point1Degrees,
  // ignore: public_member_api_docs
  plagHamincha18Degrees,
  // ignore: public_member_api_docs
  plagHamincha19Point8Degrees,
  // ignore: public_member_api_docs
  plagHamincha26Degrees,
  // ignore: public_member_api_docs
  plagHamincha60Minutes,
  // ignore: public_member_api_docs
  plagHamincha72Minutes,
  // ignore: public_member_api_docs
  plagHamincha72MinutesZmanis,
  // ignore: public_member_api_docs
  plagHamincha90Minutes,
  // ignore: public_member_api_docs
  plagHamincha90MinutesZmanis,
  // ignore: public_member_api_docs
  plagHamincha96Minutes,
  // ignore: public_member_api_docs
  plagHamincha96MinutesZmanis,
  // ignore: public_member_api_docs
  plagHaminchaAteretTorah,
  // ignore: public_member_api_docs
  plagHaminchaBaalHatanya,
  // ignore: public_member_api_docs
  plagHaminchaGra,
  // ignore: public_member_api_docs
  plagHaminchaGrafixedLocalChatzosToSunset,
  // ignore: public_member_api_docs
  polarSunriseBenIshChai,
  // ignore: public_member_api_docs
  polarSunsetBenIshChai,
  // ignore: public_member_api_docs
  samuchLeMinchaKetana16Point1Degrees,
  // ignore: public_member_api_docs
  samuchLeMinchaKetana72Minutes,
  // ignore: public_member_api_docs
  samuchLeMinchaKetanaGra,
  // ignore: public_member_api_docs
  seaLevelSunrise,
  // ignore: public_member_api_docs
  seaLevelSunset,
  // ignore: public_member_api_docs
  sofZmanAchilasChametzBaalHatanya,
  // ignore: public_member_api_docs
  sofZmanAchilasChametzGra,
  // ignore: public_member_api_docs
  sofZmanAchilasChametzMga16Point1Degrees,
  // ignore: public_member_api_docs
  sofZmanAchilasChametzMga72Minutes,
  // ignore: public_member_api_docs
  sofZmanAchilasChametzMga72MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanBiurChametzBaalHatanya,
  // ignore: public_member_api_docs
  sofZmanBiurChametzGra,
  // ignore: public_member_api_docs
  sofZmanBiurChametzMga16Point1Degrees,
  // ignore: public_member_api_docs
  sofZmanBiurChametzMga72Minutes,
  // ignore: public_member_api_docs
  sofZmanBiurChametzMga72MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanKidushLevana15Days,
  // ignore: public_member_api_docs
  sofZmanKidushLevanaBetweenMoldos,
  // ignore: public_member_api_docs
  sofZmanShma3HoursBeforeChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees,
  // ignore: public_member_api_docs
  sofZmanShmaAlos16Point1ToSunset,
  // ignore: public_member_api_docs
  sofZmanShmaAteretTorah,
  // ignore: public_member_api_docs
  sofZmanShmaBaalHatanya,
  // ignore: public_member_api_docs
  sofZmanShmaGra,
  // ignore: public_member_api_docs
  sofZmanShmaGrasunriseToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaMga120Minutes,
  // ignore: public_member_api_docs
  sofZmanShmaMga16Point1Degrees,
  // ignore: public_member_api_docs
  sofZmanShmaMga16Point1DegreesToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaMga18Degrees,
  // ignore: public_member_api_docs
  sofZmanShmaMga18DegreesToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaMga19Point8Degrees,
  // ignore: public_member_api_docs
  sofZmanShmaMga72Minutes,
  // ignore: public_member_api_docs
  sofZmanShmaMga72MinutesToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaMga72MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanShmaMga90Minutes,
  // ignore: public_member_api_docs
  sofZmanShmaMga90MinutesToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanShmaMga90MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanShmaMga96Minutes,
  // ignore: public_member_api_docs
  sofZmanShmaMga96MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanTfila2HoursBeforeChatzos,
  // ignore: public_member_api_docs
  sofZmanTfilaAteretTorah,
  // ignore: public_member_api_docs
  sofZmanTfilaBaalHatanya,
  // ignore: public_member_api_docs
  sofZmanTfilaGra,
  // ignore: public_member_api_docs
  sofZmanTfilaGrasunriseToFixedLocalChatzos,
  // ignore: public_member_api_docs
  sofZmanTfilaMga120Minutes,
  // ignore: public_member_api_docs
  sofZmanTfilaMga16Point1Degrees,
  // ignore: public_member_api_docs
  sofZmanTfilaMga18Degrees,
  // ignore: public_member_api_docs
  sofZmanTfilaMga19Point8Degrees,
  // ignore: public_member_api_docs
  sofZmanTfilaMga72Minutes,
  // ignore: public_member_api_docs
  sofZmanTfilaMga72MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanTfilaMga90Minutes,
  // ignore: public_member_api_docs
  sofZmanTfilaMga90MinutesZmanis,
  // ignore: public_member_api_docs
  sofZmanTfilaMga96Minutes,
  // ignore: public_member_api_docs
  sofZmanTfilaMga96MinutesZmanis,
  // ignore: public_member_api_docs
  solarMidnight,
  // ignore: public_member_api_docs
  sunTransit,
  // ignore: public_member_api_docs
  tchilasZmanKidushLevana3Days,
  // ignore: public_member_api_docs
  tchilasZmanKidushLevana7Days,
  // ignore: public_member_api_docs
  tzais120Minutes,
  // ignore: public_member_api_docs
  tzais120Zmanis,
  // ignore: public_member_api_docs
  tzais16Point1Degrees,
  // ignore: public_member_api_docs
  tzais18Degrees,
  // ignore: public_member_api_docs
  tzais19Point8Degrees,
  // ignore: public_member_api_docs
  tzais26Degrees,
  // ignore: public_member_api_docs
  tzais50Minutes,
  // ignore: public_member_api_docs
  tzais60Minutes,
  // ignore: public_member_api_docs
  tzais72Minutes,
  // ignore: public_member_api_docs
  tzais72Zmanis,
  // ignore: public_member_api_docs
  tzais90Minutes,
  // ignore: public_member_api_docs
  tzais90Zmanis,
  // ignore: public_member_api_docs
  tzais96Minutes,
  // ignore: public_member_api_docs
  tzais96Zmanis,
  // ignore: public_member_api_docs
  tzaisAteretTorah,
  // ignore: public_member_api_docs
  tzaisBaalHatanya,
  // ignore: public_member_api_docs
  tzaisGeonim3Point7Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim3Point8Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim4Point42Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim4Point66Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim4Point8Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim5Point95Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim6Point45Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim7Point083Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim7Point67Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim8Point5Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim9Point3Degrees,
  // ignore: public_member_api_docs
  tzaisGeonim9Point75Degrees;

}

// dart format on
