// generated by diplomat-tool
import type { SideCode } from "./SideCode"
import type { TractateCode } from "./TractateCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type AmudResult_obj = {
    tractate: TractateCode;
    page: number;
    side: SideCode;
};



export class AmudResult {
    get tractate(): TractateCode;
    set tractate(value: TractateCode);
    get page(): number;
    set page(value: number);
    get side(): SideCode;
    set side(value: SideCode);
    /** @internal */
    static fromFields(structObj : AmudResult_obj) : AmudResult;

    /**
    * Create `AmudResult` from an object that contains all of `AmudResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: AmudResult_obj);

}