// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Calculator configuration (durations in minutes).
 */
export class CalculatorConfig {
    #candleLightingOffsetMinutes;
    get candleLightingOffsetMinutes() {
        return this.#candleLightingOffsetMinutes;
    }
    set candleLightingOffsetMinutes(value){
        this.#candleLightingOffsetMinutes = value;
    }
    #useAstronomicalChatzosForOtherZmanim;
    get useAstronomicalChatzosForOtherZmanim() {
        return this.#useAstronomicalChatzosForOtherZmanim;
    }
    set useAstronomicalChatzosForOtherZmanim(value){
        this.#useAstronomicalChatzosForOtherZmanim = value;
    }
    #useElevation;
    get useElevation() {
        return this.#useElevation;
    }
    set useElevation(value){
        this.#useElevation = value;
    }
    #ateretTorahSunsetOffsetMinutes;
    get ateretTorahSunsetOffsetMinutes() {
        return this.#ateretTorahSunsetOffsetMinutes;
    }
    set ateretTorahSunsetOffsetMinutes(value){
        this.#ateretTorahSunsetOffsetMinutes = value;
    }
    #useAstronomicalChatzos;
    get useAstronomicalChatzos() {
        return this.#useAstronomicalChatzos;
    }
    set useAstronomicalChatzos(value){
        this.#useAstronomicalChatzos = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new CalculatorConfig(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("CalculatorConfig's constructor takes an object of CalculatorConfig's fields.");
        }

        if ("candleLightingOffsetMinutes" in structObj) {
            this.#candleLightingOffsetMinutes = structObj.candleLightingOffsetMinutes;
        } else {
            throw new Error("Missing required field candleLightingOffsetMinutes.");
        }

        if ("useAstronomicalChatzosForOtherZmanim" in structObj) {
            this.#useAstronomicalChatzosForOtherZmanim = structObj.useAstronomicalChatzosForOtherZmanim;
        } else {
            throw new Error("Missing required field useAstronomicalChatzosForOtherZmanim.");
        }

        if ("useElevation" in structObj) {
            this.#useElevation = structObj.useElevation;
        } else {
            throw new Error("Missing required field useElevation.");
        }

        if ("ateretTorahSunsetOffsetMinutes" in structObj) {
            this.#ateretTorahSunsetOffsetMinutes = structObj.ateretTorahSunsetOffsetMinutes;
        } else {
            throw new Error("Missing required field ateretTorahSunsetOffsetMinutes.");
        }

        if ("useAstronomicalChatzos" in structObj) {
            this.#useAstronomicalChatzos = structObj.useAstronomicalChatzos;
        } else {
            throw new Error("Missing required field useAstronomicalChatzos.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 16;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof CalculatorConfig) {
            return obj;
        }

        return CalculatorConfig.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#candleLightingOffsetMinutes, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#useAstronomicalChatzosForOtherZmanim, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 5, this.#useElevation, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 8, this.#ateretTorahSunsetOffsetMinutes, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 12, this.#useAstronomicalChatzos, Uint8Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("CalculatorConfig._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const candleLightingOffsetMinutesDeref = (new Int32Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.candleLightingOffsetMinutes = candleLightingOffsetMinutesDeref;
        const useAstronomicalChatzosForOtherZmanimDeref = (new Uint8Array(wasm.memory.buffer, ptr + 4, 1))[0] === 1;
        structObj.useAstronomicalChatzosForOtherZmanim = useAstronomicalChatzosForOtherZmanimDeref;
        const useElevationDeref = (new Uint8Array(wasm.memory.buffer, ptr + 5, 1))[0] === 1;
        structObj.useElevation = useElevationDeref;
        const ateretTorahSunsetOffsetMinutesDeref = (new Int32Array(wasm.memory.buffer, ptr + 8, 1))[0];
        structObj.ateretTorahSunsetOffsetMinutes = ateretTorahSunsetOffsetMinutesDeref;
        const useAstronomicalChatzosDeref = (new Uint8Array(wasm.memory.buffer, ptr + 12, 1))[0] === 1;
        structObj.useAstronomicalChatzos = useAstronomicalChatzosDeref;

        return new CalculatorConfig(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}