// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type CalculatorConfig_obj = {
    candleLightingOffsetMinutes: number;
    useAstronomicalChatzosForOtherZmanim: boolean;
    useElevation: boolean;
    ateretTorahSunsetOffsetMinutes: number;
    useAstronomicalChatzos: boolean;
};



/**
 * Calculator configuration (durations in minutes).
 */
export class CalculatorConfig {
    get candleLightingOffsetMinutes(): number;
    set candleLightingOffsetMinutes(value: number);
    get useAstronomicalChatzosForOtherZmanim(): boolean;
    set useAstronomicalChatzosForOtherZmanim(value: boolean);
    get useElevation(): boolean;
    set useElevation(value: boolean);
    get ateretTorahSunsetOffsetMinutes(): number;
    set ateretTorahSunsetOffsetMinutes(value: number);
    get useAstronomicalChatzos(): boolean;
    set useAstronomicalChatzos(value: boolean);
    /** @internal */
    static fromFields(structObj : CalculatorConfig_obj) : CalculatorConfig;

    /**
    * Create `CalculatorConfig` from an object that contains all of `CalculatorConfig`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: CalculatorConfig_obj);

}