// generated by diplomat-tool
import type { CivilDate } from "./CivilDate"
import type { CivilDate_obj } from "./CivilDate"
import type { HebrewDate } from "./HebrewDate"
import type { HebrewDate_obj } from "./HebrewDate"
import type { HolidayList } from "./HolidayList"
import type { ParshaCode } from "./ParshaCode"
import type { YearLengthTypeCode } from "./YearLengthTypeCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Dart entry point: construct once and call instance methods.
 */
export class Calendar {
    /** @internal */
    get ffiValue(): pointer;


    gregorianToHebrew(date: CivilDate_obj): HebrewDate | null;

    hebrewToGregorian(date: HebrewDate_obj): CivilDate | null;

    holidaysOnDate(date: CivilDate_obj, inIsrael: boolean, useModernHolidays: boolean): HolidayList | null;

    isAssurBemelacha(date: CivilDate_obj, inIsrael: boolean): boolean | null;

    hasCandleLighting(date: CivilDate_obj, inIsrael: boolean): boolean | null;

    todaysParsha(date: CivilDate_obj, inIsrael: boolean): ParshaCode | null;

    specialParsha(date: CivilDate_obj, inIsrael: boolean): ParshaCode | null;

    upcomingParsha(date: CivilDate_obj, inIsrael: boolean): ParshaCode | null;

    daysInHebrewYear(year: number): number | null;

    daysInHebrewMonth(year: number, month: number): number | null;

    isHebrewLeapYear(year: number): boolean;

    cheshvanKislevKviah(year: number): YearLengthTypeCode | null;

    constructor();
}