// generated by diplomat-tool
import { CivilDate } from "./CivilDate.mjs"
import { HebrewDate } from "./HebrewDate.mjs"
import { HolidayList } from "./HolidayList.mjs"
import { ParshaCode } from "./ParshaCode.mjs"
import { YearLengthTypeCode } from "./YearLengthTypeCode.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Calendar_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Calendar_destroy(ptr);
});

/**
 * Dart entry point: construct once and call instance methods.
 */
export class Calendar {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Calendar is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Calendar_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    #defaultConstructor() {

        const result = wasm.Calendar_new();

        try {
            return new Calendar(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    gregorianToHebrew(date) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.Calendar_gregorian_to_hebrew(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false));

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return HebrewDate._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    hebrewToGregorian(date) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.Calendar_hebrew_to_gregorian(diplomatReceive.buffer, this.ffiValue, HebrewDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(HebrewDate._sizeBytes), functionCleanupArena, {}, false));

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return CivilDate._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    holidaysOnDate(date, inIsrael, useModernHolidays) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();


        const result = wasm.Calendar_holidays_on_date(this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael, useModernHolidays);

        try {
            return result === 0 ? null : new HolidayList(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

        }
    }

    isAssurBemelacha(date, inIsrael) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 2, 1, true);


        const result = wasm.Calendar_is_assur_bemelacha(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return (new Uint8Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0] === 1;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    hasCandleLighting(date, inIsrael) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 2, 1, true);


        const result = wasm.Calendar_has_candle_lighting(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return (new Uint8Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0] === 1;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    todaysParsha(date, inIsrael) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Calendar_todays_parsha(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    specialParsha(date, inIsrael) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Calendar_special_parsha(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    upcomingParsha(date, inIsrael) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Calendar_upcoming_parsha(diplomatReceive.buffer, this.ffiValue, CivilDate._fromSuppliedValue(diplomatRuntime.internalConstructor, date)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(CivilDate._sizeBytes), functionCleanupArena, {}, false), inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    daysInHebrewYear(year) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Calendar_days_in_hebrew_year(diplomatReceive.buffer, this.ffiValue, year);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return (new Int32Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0];
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    daysInHebrewMonth(year, month) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 2, 1, true);


        const result = wasm.Calendar_days_in_hebrew_month(diplomatReceive.buffer, this.ffiValue, year, month);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return (new Uint8Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0];
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    isHebrewLeapYear(year) {

        const result = wasm.Calendar_is_hebrew_leap_year(this.ffiValue, year);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    cheshvanKislevKviah(year) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Calendar_cheshvan_kislev_kviah(diplomatReceive.buffer, this.ffiValue, year);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new YearLengthTypeCode(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    constructor() {
        if (arguments[0] === diplomatRuntime.exposeConstructor) {
            return this.#internalConstructor(...Array.prototype.slice.call(arguments, 1));
        } else if (arguments[0] === diplomatRuntime.internalConstructor) {
            return this.#internalConstructor(...arguments);
        } else {
            return this.#defaultConstructor(...arguments);
        }
    }
}