// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type CivilDate_obj = {
    year: number;
    month: number;
    day: number;
};



/**
 * Gregorian civil date (year, month, day).
 */
export class CivilDate {
    get year(): number;
    set year(value: number);
    get month(): number;
    set month(value: number);
    get day(): number;
    set day(value: number);
    /** @internal */
    static fromFields(structObj : CivilDate_obj) : CivilDate;

    /**
    * Create `CivilDate` from an object that contains all of `CivilDate`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: CivilDate_obj);

}