// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Gregorian civil date (year, month, day).
 */
export class CivilDate {
    #year;
    get year() {
        return this.#year;
    }
    set year(value){
        this.#year = value;
    }
    #month;
    get month() {
        return this.#month;
    }
    set month(value){
        this.#month = value;
    }
    #day;
    get day() {
        return this.#day;
    }
    set day(value){
        this.#day = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new CivilDate(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("CivilDate's constructor takes an object of CivilDate's fields.");
        }

        if ("year" in structObj) {
            this.#year = structObj.year;
        } else {
            throw new Error("Missing required field year.");
        }

        if ("month" in structObj) {
            this.#month = structObj.month;
        } else {
            throw new Error("Missing required field month.");
        }

        if ("day" in structObj) {
            this.#day = structObj.day;
        } else {
            throw new Error("Missing required field day.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 8;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof CivilDate) {
            return obj;
        }

        return CivilDate.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#year, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#month, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 5, this.#day, Uint8Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("CivilDate._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const yearDeref = (new Int32Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.year = yearDeref;
        const monthDeref = (new Uint8Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.month = monthDeref;
        const dayDeref = (new Uint8Array(wasm.memory.buffer, ptr + 5, 1))[0];
        structObj.day = dayDeref;

        return new CivilDate(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}