// generated by diplomat-tool
import { TractateCode } from "./TractateCode.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class DafResult {
    #tractate;
    get tractate() {
        return this.#tractate;
    }
    set tractate(value){
        this.#tractate = value;
    }
    #page;
    get page() {
        return this.#page;
    }
    set page(value){
        this.#page = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new DafResult(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("DafResult's constructor takes an object of DafResult's fields.");
        }

        if ("tractate" in structObj) {
            this.#tractate = structObj.tractate;
        } else {
            throw new Error("Missing required field tractate.");
        }

        if ("page" in structObj) {
            this.#page = structObj.page;
        } else {
            throw new Error("Missing required field page.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 8;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof DafResult) {
            return obj;
        }

        return DafResult.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#tractate.ffiValue, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#page, Uint16Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("DafResult._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const tractateDeref = diplomatRuntime.enumDiscriminant(wasm, ptr);
        structObj.tractate = new TractateCode(diplomatRuntime.internalConstructor, tractateDeref);
        const pageDeref = (new Uint16Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.page = pageDeref;

        return new DafResult(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}