// generated by diplomat-tool
import type { TractateCode } from "./TractateCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type DafResult_obj = {
    tractate: TractateCode;
    page: number;
};



export class DafResult {
    get tractate(): TractateCode;
    set tractate(value: TractateCode);
    get page(): number;
    set page(value: number);
    /** @internal */
    static fromFields(structObj : DafResult_obj) : DafResult;

    /**
    * Create `DafResult` from an object that contains all of `DafResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: DafResult_obj);

}