// generated by diplomat-tool
import { ZmanimErrorCode } from "./ZmanimErrorCode.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const FfiLocation_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.FfiLocation_destroy(ptr);
});

export class FfiLocation {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("FfiLocation is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            FfiLocation_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a location. Pass an empty timezone string when unknown.
     */
    static new_(latitude, longitude, elevation, timezoneIana) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const timezoneIanaSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, timezoneIana)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.FfiLocation_new(diplomatReceive.buffer, latitude, longitude, elevation, timezoneIanaSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('ZmanimErrorCode.' + cause.value, { cause });
            }
            return new FfiLocation(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}