// generated by diplomat-tool
import type { ZmanimErrorCode } from "./ZmanimErrorCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class FfiLocation {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a location. Pass an empty timezone string when unknown.
     */
    static new_(latitude: number, longitude: number, elevation: number, timezoneIana: string): FfiLocation;
}