// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class HolidayCode {
    #value = undefined;

    static #values = new Map([
        ["ErevPesach", 0],
        ["Pesach", 1],
        ["CholHamoedPesach", 2],
        ["PesachSheni", 3],
        ["ErevShavuos", 4],
        ["Shavuos", 5],
        ["SeventeenthOfTammuz", 6],
        ["TishahBav", 7],
        ["TuBav", 8],
        ["ErevRoshHashana", 9],
        ["RoshHashana", 10],
        ["FastOfGedalyah", 11],
        ["ErevYomKippur", 12],
        ["YomKippur", 13],
        ["ErevSuccos", 14],
        ["Succos", 15],
        ["CholHamoedSuccos", 16],
        ["HoshanaRabbah", 17],
        ["SheminiAtzeres", 18],
        ["SimchasTorah", 19],
        ["Chanukah", 20],
        ["TenthOfTeves", 21],
        ["TuBshvat", 22],
        ["FastOfEsther", 23],
        ["Purim", 24],
        ["ShushanPurim", 25],
        ["PurimKatan", 26],
        ["RoshChodesh", 27],
        ["YomHaShoah", 28],
        ["YomHazikaron", 29],
        ["YomHaatzmaut", 30],
        ["YomYerushalayim", 31],
        ["LagBomer", 32],
        ["ShushanPurimKatan", 33],
        ["IsruChag", 34],
        ["YomKippurKatan", 35],
        ["Behab", 36],
        ["FastOfTheFirstborn", 37],
        ["CountOfTheOmer", 38],
        ["BirchasHachamah", 39],
        ["MacharHachodesh", 40],
        ["ShabbosMevarchim", 41]
    ]);

    static getAllEntries() {
        return HolidayCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return HolidayCode.#objectValues[arguments[1]];
        }

        if (value instanceof HolidayCode) {
            return value;
        }

        let intVal = HolidayCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return HolidayCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a HolidayCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new HolidayCode(value);
    }

    get value(){
        return [...HolidayCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 16),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 17),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 18),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 19),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 20),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 21),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 22),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 23),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 24),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 25),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 26),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 27),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 28),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 29),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 30),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 31),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 32),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 33),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 34),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 35),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 36),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 37),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 38),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 39),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 40),
        new HolidayCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 41),
    ];

    static ErevPesach = HolidayCode.#objectValues[0];
    static Pesach = HolidayCode.#objectValues[1];
    static CholHamoedPesach = HolidayCode.#objectValues[2];
    static PesachSheni = HolidayCode.#objectValues[3];
    static ErevShavuos = HolidayCode.#objectValues[4];
    static Shavuos = HolidayCode.#objectValues[5];
    static SeventeenthOfTammuz = HolidayCode.#objectValues[6];
    static TishahBav = HolidayCode.#objectValues[7];
    static TuBav = HolidayCode.#objectValues[8];
    static ErevRoshHashana = HolidayCode.#objectValues[9];
    static RoshHashana = HolidayCode.#objectValues[10];
    static FastOfGedalyah = HolidayCode.#objectValues[11];
    static ErevYomKippur = HolidayCode.#objectValues[12];
    static YomKippur = HolidayCode.#objectValues[13];
    static ErevSuccos = HolidayCode.#objectValues[14];
    static Succos = HolidayCode.#objectValues[15];
    static CholHamoedSuccos = HolidayCode.#objectValues[16];
    static HoshanaRabbah = HolidayCode.#objectValues[17];
    static SheminiAtzeres = HolidayCode.#objectValues[18];
    static SimchasTorah = HolidayCode.#objectValues[19];
    static Chanukah = HolidayCode.#objectValues[20];
    static TenthOfTeves = HolidayCode.#objectValues[21];
    static TuBshvat = HolidayCode.#objectValues[22];
    static FastOfEsther = HolidayCode.#objectValues[23];
    static Purim = HolidayCode.#objectValues[24];
    static ShushanPurim = HolidayCode.#objectValues[25];
    static PurimKatan = HolidayCode.#objectValues[26];
    static RoshChodesh = HolidayCode.#objectValues[27];
    static YomHaShoah = HolidayCode.#objectValues[28];
    static YomHazikaron = HolidayCode.#objectValues[29];
    static YomHaatzmaut = HolidayCode.#objectValues[30];
    static YomYerushalayim = HolidayCode.#objectValues[31];
    static LagBomer = HolidayCode.#objectValues[32];
    static ShushanPurimKatan = HolidayCode.#objectValues[33];
    static IsruChag = HolidayCode.#objectValues[34];
    static YomKippurKatan = HolidayCode.#objectValues[35];
    static Behab = HolidayCode.#objectValues[36];
    static FastOfTheFirstborn = HolidayCode.#objectValues[37];
    static CountOfTheOmer = HolidayCode.#objectValues[38];
    static BirchasHachamah = HolidayCode.#objectValues[39];
    static MacharHachodesh = HolidayCode.#objectValues[40];
    static ShabbosMevarchim = HolidayCode.#objectValues[41];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}