// generated by diplomat-tool
import type { HolidayCode } from "./HolidayCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type HolidayEntry_obj = {
    code: HolidayCode;
    subDay: number;
};



/**
 * A holiday occurring on a date, with an optional sub-day (Chanukah, Omer).
 */
export class HolidayEntry {
    get code(): HolidayCode;
    set code(value: HolidayCode);
    get subDay(): number;
    set subDay(value: number);
    /** @internal */
    static fromFields(structObj : HolidayEntry_obj) : HolidayEntry;

    /**
    * Create `HolidayEntry` from an object that contains all of `HolidayEntry`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: HolidayEntry_obj);

}