// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class HolidayCode {

    /** @internal */
    static fromValue(value: HolidayCode | string): HolidayCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static ErevPesach : HolidayCode;
    static Pesach : HolidayCode;
    static CholHamoedPesach : HolidayCode;
    static PesachSheni : HolidayCode;
    static ErevShavuos : HolidayCode;
    static Shavuos : HolidayCode;
    static SeventeenthOfTammuz : HolidayCode;
    static TishahBav : HolidayCode;
    static TuBav : HolidayCode;
    static ErevRoshHashana : HolidayCode;
    static RoshHashana : HolidayCode;
    static FastOfGedalyah : HolidayCode;
    static ErevYomKippur : HolidayCode;
    static YomKippur : HolidayCode;
    static ErevSuccos : HolidayCode;
    static Succos : HolidayCode;
    static CholHamoedSuccos : HolidayCode;
    static HoshanaRabbah : HolidayCode;
    static SheminiAtzeres : HolidayCode;
    static SimchasTorah : HolidayCode;
    static Chanukah : HolidayCode;
    static TenthOfTeves : HolidayCode;
    static TuBshvat : HolidayCode;
    static FastOfEsther : HolidayCode;
    static Purim : HolidayCode;
    static ShushanPurim : HolidayCode;
    static PurimKatan : HolidayCode;
    static RoshChodesh : HolidayCode;
    static YomHaShoah : HolidayCode;
    static YomHazikaron : HolidayCode;
    static YomHaatzmaut : HolidayCode;
    static YomYerushalayim : HolidayCode;
    static LagBomer : HolidayCode;
    static ShushanPurimKatan : HolidayCode;
    static IsruChag : HolidayCode;
    static YomKippurKatan : HolidayCode;
    static Behab : HolidayCode;
    static FastOfTheFirstborn : HolidayCode;
    static CountOfTheOmer : HolidayCode;
    static BirchasHachamah : HolidayCode;
    static MacharHachodesh : HolidayCode;
    static ShabbosMevarchim : HolidayCode;


    constructor(value: HolidayCode | string );
}