// generated by diplomat-tool
import type { AmudResult } from "./AmudResult"
import type { DafResult } from "./DafResult"
import type { MishnasResult } from "./MishnasResult"
import type { PirkeiAvosResult } from "./PirkeiAvosResult"
import type { TehillimResult } from "./TehillimResult"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Dart entry point: construct once and call instance methods.
 */
export class Limudim {
    /** @internal */
    get ffiValue(): pointer;


    dafYomiBavli(year: number, month: number, day: number): DafResult | null;

    dafYomiYerushalmi(year: number, month: number, day: number): DafResult | null;

    dafHashavuaBavli(year: number, month: number, day: number): DafResult | null;

    amudYomiBavliDirshu(year: number, month: number, day: number): AmudResult | null;

    mishnaYomis(year: number, month: number, day: number): MishnasResult | null;

    pirkeiAvos(year: number, month: number, day: number, inIsrael: boolean): PirkeiAvosResult | null;

    tehillimMonthly(year: number, month: number, day: number): TehillimResult | null;

    constructor();
}