// generated by diplomat-tool
import { AmudResult } from "./AmudResult.mjs"
import { DafResult } from "./DafResult.mjs"
import { MishnasResult } from "./MishnasResult.mjs"
import { PirkeiAvosResult } from "./PirkeiAvosResult.mjs"
import { TehillimResult } from "./TehillimResult.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Limudim_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Limudim_destroy(ptr);
});

/**
 * Dart entry point: construct once and call instance methods.
 */
export class Limudim {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Limudim is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Limudim_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    #defaultConstructor() {

        const result = wasm.Limudim_new();

        try {
            return new Limudim(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    dafYomiBavli(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.Limudim_daf_yomi_bavli(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return DafResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    dafYomiYerushalmi(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.Limudim_daf_yomi_yerushalmi(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return DafResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    dafHashavuaBavli(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.Limudim_daf_hashavua_bavli(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return DafResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    amudYomiBavliDirshu(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 13, 4, true);


        const result = wasm.Limudim_amud_yomi_bavli_dirshu(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return AmudResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    mishnaYomis(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 25, 4, true);


        const result = wasm.Limudim_mishna_yomis(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return MishnasResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    pirkeiAvos(year, month, day, inIsrael) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 4, 1, true);


        const result = wasm.Limudim_pirkei_avos(diplomatReceive.buffer, this.ffiValue, year, month, day, inIsrael);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return PirkeiAvosResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    tehillimMonthly(year, month, day) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 2, true);


        const result = wasm.Limudim_tehillim_monthly(diplomatReceive.buffer, this.ffiValue, year, month, day);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return TehillimResult._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    constructor() {
        if (arguments[0] === diplomatRuntime.exposeConstructor) {
            return this.#internalConstructor(...Array.prototype.slice.call(arguments, 1));
        } else if (arguments[0] === diplomatRuntime.internalConstructor) {
            return this.#internalConstructor(...arguments);
        } else {
            return this.#defaultConstructor(...arguments);
        }
    }
}