// generated by diplomat-tool
import type { TractateCode } from "./TractateCode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type MishnaResult_obj = {
    tractate: TractateCode;
    chapter: number;
    mishna: number;
};



export class MishnaResult {
    get tractate(): TractateCode;
    set tractate(value: TractateCode);
    get chapter(): number;
    set chapter(value: number);
    get mishna(): number;
    set mishna(value: number);
    /** @internal */
    static fromFields(structObj : MishnaResult_obj) : MishnaResult;

    /**
    * Create `MishnaResult` from an object that contains all of `MishnaResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: MishnaResult_obj);

}