// generated by diplomat-tool
import type { MishnaResult } from "./MishnaResult"
import type { MishnaResult_obj } from "./MishnaResult"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type MishnasResult_obj = {
    start: MishnaResult_obj;
    end: MishnaResult_obj;
};



export class MishnasResult {
    get start(): MishnaResult;
    set start(value: MishnaResult);
    get end(): MishnaResult;
    set end(value: MishnaResult);
    /** @internal */
    static fromFields(structObj : MishnasResult_obj) : MishnasResult;

    /**
    * Create `MishnasResult` from an object that contains all of `MishnasResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: MishnasResult_obj);

}