// generated by diplomat-tool
import { MishnaResult } from "./MishnaResult.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class MishnasResult {
    #start;
    get start() {
        return this.#start;
    }
    set start(value){
        this.#start = value;
    }
    #end;
    get end() {
        return this.#end;
    }
    set end(value){
        this.#end = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new MishnasResult(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("MishnasResult's constructor takes an object of MishnasResult's fields.");
        }

        if ("start" in structObj) {
            this.#start = MishnaResult._fromSuppliedValue(diplomatRuntime.internalConstructor, structObj.start);
        } else {
            throw new Error("Missing required field start.");
        }

        if ("end" in structObj) {
            this.#end = MishnaResult._fromSuppliedValue(diplomatRuntime.internalConstructor, structObj.end);
        } else {
            throw new Error("Missing required field end.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 24;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof MishnasResult) {
            return obj;
        }

        return MishnasResult.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        MishnaResult._fromSuppliedValue(diplomatRuntime.internalConstructor, this.#start)._writeToArrayBuffer(arrayBuffer, offset + 0, functionCleanupArena, {});
        MishnaResult._fromSuppliedValue(diplomatRuntime.internalConstructor, this.#end)._writeToArrayBuffer(arrayBuffer, offset + 12, functionCleanupArena, {});
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("MishnasResult._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const startDeref = ptr;
        structObj.start = MishnaResult._fromFFI(diplomatRuntime.internalConstructor, startDeref);
        const endDeref = ptr + 12;
        structObj.end = MishnaResult._fromFFI(diplomatRuntime.internalConstructor, endDeref);

        return new MishnasResult(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}