// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class ParshaCode {
    #value = undefined;

    static #values = new Map([
        ["Bereshis", 0],
        ["Noach", 1],
        ["LechLecha", 2],
        ["Vayera", 3],
        ["ChayeiSara", 4],
        ["Toldos", 5],
        ["Vayetzei", 6],
        ["Vayishlach", 7],
        ["Vayeshev", 8],
        ["Miketz", 9],
        ["Vayigash", 10],
        ["Vayechi", 11],
        ["Shemos", 12],
        ["Vaera", 13],
        ["Bo", 14],
        ["Beshalach", 15],
        ["Yisro", 16],
        ["Mishpatim", 17],
        ["Terumah", 18],
        ["Tetzaveh", 19],
        ["KiSisa", 20],
        ["Vayakhel", 21],
        ["Pekudei", 22],
        ["Vayikra", 23],
        ["Tzav", 24],
        ["Shmini", 25],
        ["Tazria", 26],
        ["Metzora", 27],
        ["AchreiMos", 28],
        ["Kedoshim", 29],
        ["Emor", 30],
        ["Behar", 31],
        ["Bechukosai", 32],
        ["Bamidbar", 33],
        ["Nasso", 34],
        ["Behaaloscha", 35],
        ["Shlach", 36],
        ["Korach", 37],
        ["Chukas", 38],
        ["Balak", 39],
        ["Pinchas", 40],
        ["Matos", 41],
        ["Masei", 42],
        ["Devarim", 43],
        ["Vaeschanan", 44],
        ["Eikev", 45],
        ["Reeh", 46],
        ["Shoftim", 47],
        ["KiSeitzei", 48],
        ["KiSavo", 49],
        ["Nitzavim", 50],
        ["Vayeilech", 51],
        ["HaAzinu", 52],
        ["VezosHabracha", 53],
        ["VayakhelPekudei", 54],
        ["TazriaMetzora", 55],
        ["AchreiMosKedoshim", 56],
        ["BeharBechukosai", 57],
        ["ChukasBalak", 58],
        ["MatosMasei", 59],
        ["NitzavimVayeilech", 60],
        ["Shekalim", 61],
        ["Zachor", 62],
        ["Parah", 63],
        ["Hachodesh", 64],
        ["Shuva", 65],
        ["Shira", 66],
        ["Hagadol", 67],
        ["Chazon", 68],
        ["Nachamu", 69]
    ]);

    static getAllEntries() {
        return ParshaCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return ParshaCode.#objectValues[arguments[1]];
        }

        if (value instanceof ParshaCode) {
            return value;
        }

        let intVal = ParshaCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return ParshaCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a ParshaCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new ParshaCode(value);
    }

    get value(){
        return [...ParshaCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 16),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 17),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 18),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 19),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 20),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 21),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 22),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 23),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 24),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 25),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 26),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 27),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 28),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 29),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 30),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 31),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 32),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 33),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 34),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 35),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 36),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 37),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 38),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 39),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 40),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 41),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 42),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 43),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 44),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 45),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 46),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 47),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 48),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 49),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 50),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 51),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 52),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 53),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 54),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 55),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 56),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 57),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 58),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 59),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 60),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 61),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 62),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 63),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 64),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 65),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 66),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 67),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 68),
        new ParshaCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 69),
    ];

    static Bereshis = ParshaCode.#objectValues[0];
    static Noach = ParshaCode.#objectValues[1];
    static LechLecha = ParshaCode.#objectValues[2];
    static Vayera = ParshaCode.#objectValues[3];
    static ChayeiSara = ParshaCode.#objectValues[4];
    static Toldos = ParshaCode.#objectValues[5];
    static Vayetzei = ParshaCode.#objectValues[6];
    static Vayishlach = ParshaCode.#objectValues[7];
    static Vayeshev = ParshaCode.#objectValues[8];
    static Miketz = ParshaCode.#objectValues[9];
    static Vayigash = ParshaCode.#objectValues[10];
    static Vayechi = ParshaCode.#objectValues[11];
    static Shemos = ParshaCode.#objectValues[12];
    static Vaera = ParshaCode.#objectValues[13];
    static Bo = ParshaCode.#objectValues[14];
    static Beshalach = ParshaCode.#objectValues[15];
    static Yisro = ParshaCode.#objectValues[16];
    static Mishpatim = ParshaCode.#objectValues[17];
    static Terumah = ParshaCode.#objectValues[18];
    static Tetzaveh = ParshaCode.#objectValues[19];
    static KiSisa = ParshaCode.#objectValues[20];
    static Vayakhel = ParshaCode.#objectValues[21];
    static Pekudei = ParshaCode.#objectValues[22];
    static Vayikra = ParshaCode.#objectValues[23];
    static Tzav = ParshaCode.#objectValues[24];
    static Shmini = ParshaCode.#objectValues[25];
    static Tazria = ParshaCode.#objectValues[26];
    static Metzora = ParshaCode.#objectValues[27];
    static AchreiMos = ParshaCode.#objectValues[28];
    static Kedoshim = ParshaCode.#objectValues[29];
    static Emor = ParshaCode.#objectValues[30];
    static Behar = ParshaCode.#objectValues[31];
    static Bechukosai = ParshaCode.#objectValues[32];
    static Bamidbar = ParshaCode.#objectValues[33];
    static Nasso = ParshaCode.#objectValues[34];
    static Behaaloscha = ParshaCode.#objectValues[35];
    static Shlach = ParshaCode.#objectValues[36];
    static Korach = ParshaCode.#objectValues[37];
    static Chukas = ParshaCode.#objectValues[38];
    static Balak = ParshaCode.#objectValues[39];
    static Pinchas = ParshaCode.#objectValues[40];
    static Matos = ParshaCode.#objectValues[41];
    static Masei = ParshaCode.#objectValues[42];
    static Devarim = ParshaCode.#objectValues[43];
    static Vaeschanan = ParshaCode.#objectValues[44];
    static Eikev = ParshaCode.#objectValues[45];
    static Reeh = ParshaCode.#objectValues[46];
    static Shoftim = ParshaCode.#objectValues[47];
    static KiSeitzei = ParshaCode.#objectValues[48];
    static KiSavo = ParshaCode.#objectValues[49];
    static Nitzavim = ParshaCode.#objectValues[50];
    static Vayeilech = ParshaCode.#objectValues[51];
    static HaAzinu = ParshaCode.#objectValues[52];
    static VezosHabracha = ParshaCode.#objectValues[53];
    static VayakhelPekudei = ParshaCode.#objectValues[54];
    static TazriaMetzora = ParshaCode.#objectValues[55];
    static AchreiMosKedoshim = ParshaCode.#objectValues[56];
    static BeharBechukosai = ParshaCode.#objectValues[57];
    static ChukasBalak = ParshaCode.#objectValues[58];
    static MatosMasei = ParshaCode.#objectValues[59];
    static NitzavimVayeilech = ParshaCode.#objectValues[60];
    static Shekalim = ParshaCode.#objectValues[61];
    static Zachor = ParshaCode.#objectValues[62];
    static Parah = ParshaCode.#objectValues[63];
    static Hachodesh = ParshaCode.#objectValues[64];
    static Shuva = ParshaCode.#objectValues[65];
    static Shira = ParshaCode.#objectValues[66];
    static Hagadol = ParshaCode.#objectValues[67];
    static Chazon = ParshaCode.#objectValues[68];
    static Nachamu = ParshaCode.#objectValues[69];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}