// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ParshaCode {

    /** @internal */
    static fromValue(value: ParshaCode | string): ParshaCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Bereshis : ParshaCode;
    static Noach : ParshaCode;
    static LechLecha : ParshaCode;
    static Vayera : ParshaCode;
    static ChayeiSara : ParshaCode;
    static Toldos : ParshaCode;
    static Vayetzei : ParshaCode;
    static Vayishlach : ParshaCode;
    static Vayeshev : ParshaCode;
    static Miketz : ParshaCode;
    static Vayigash : ParshaCode;
    static Vayechi : ParshaCode;
    static Shemos : ParshaCode;
    static Vaera : ParshaCode;
    static Bo : ParshaCode;
    static Beshalach : ParshaCode;
    static Yisro : ParshaCode;
    static Mishpatim : ParshaCode;
    static Terumah : ParshaCode;
    static Tetzaveh : ParshaCode;
    static KiSisa : ParshaCode;
    static Vayakhel : ParshaCode;
    static Pekudei : ParshaCode;
    static Vayikra : ParshaCode;
    static Tzav : ParshaCode;
    static Shmini : ParshaCode;
    static Tazria : ParshaCode;
    static Metzora : ParshaCode;
    static AchreiMos : ParshaCode;
    static Kedoshim : ParshaCode;
    static Emor : ParshaCode;
    static Behar : ParshaCode;
    static Bechukosai : ParshaCode;
    static Bamidbar : ParshaCode;
    static Nasso : ParshaCode;
    static Behaaloscha : ParshaCode;
    static Shlach : ParshaCode;
    static Korach : ParshaCode;
    static Chukas : ParshaCode;
    static Balak : ParshaCode;
    static Pinchas : ParshaCode;
    static Matos : ParshaCode;
    static Masei : ParshaCode;
    static Devarim : ParshaCode;
    static Vaeschanan : ParshaCode;
    static Eikev : ParshaCode;
    static Reeh : ParshaCode;
    static Shoftim : ParshaCode;
    static KiSeitzei : ParshaCode;
    static KiSavo : ParshaCode;
    static Nitzavim : ParshaCode;
    static Vayeilech : ParshaCode;
    static HaAzinu : ParshaCode;
    static VezosHabracha : ParshaCode;
    static VayakhelPekudei : ParshaCode;
    static TazriaMetzora : ParshaCode;
    static AchreiMosKedoshim : ParshaCode;
    static BeharBechukosai : ParshaCode;
    static ChukasBalak : ParshaCode;
    static MatosMasei : ParshaCode;
    static NitzavimVayeilech : ParshaCode;
    static Shekalim : ParshaCode;
    static Zachor : ParshaCode;
    static Parah : ParshaCode;
    static Hachodesh : ParshaCode;
    static Shuva : ParshaCode;
    static Shira : ParshaCode;
    static Hagadol : ParshaCode;
    static Chazon : ParshaCode;
    static Nachamu : ParshaCode;


    constructor(value: ParshaCode | string );
}