// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Flat tagged union for Pirkei Avos (`kind`: 0 = single, 1 = combined).
 */
export class PirkeiAvosResult {
    #kind;
    get kind() {
        return this.#kind;
    }
    set kind(value){
        this.#kind = value;
    }
    #perek1;
    get perek1() {
        return this.#perek1;
    }
    set perek1(value){
        this.#perek1 = value;
    }
    #perek2;
    get perek2() {
        return this.#perek2;
    }
    set perek2(value){
        this.#perek2 = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new PirkeiAvosResult(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("PirkeiAvosResult's constructor takes an object of PirkeiAvosResult's fields.");
        }

        if ("kind" in structObj) {
            this.#kind = structObj.kind;
        } else {
            throw new Error("Missing required field kind.");
        }

        if ("perek1" in structObj) {
            this.#perek1 = structObj.perek1;
        } else {
            throw new Error("Missing required field perek1.");
        }

        if ("perek2" in structObj) {
            this.#perek2 = structObj.perek2;
        } else {
            throw new Error("Missing required field perek2.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 3;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 1;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof PirkeiAvosResult) {
            return obj;
        }

        return PirkeiAvosResult.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#kind, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 1, this.#perek1, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 2, this.#perek2, Uint8Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("PirkeiAvosResult._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const kindDeref = (new Uint8Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.kind = kindDeref;
        const perek1Deref = (new Uint8Array(wasm.memory.buffer, ptr + 1, 1))[0];
        structObj.perek1 = perek1Deref;
        const perek2Deref = (new Uint8Array(wasm.memory.buffer, ptr + 2, 1))[0];
        structObj.perek2 = perek2Deref;

        return new PirkeiAvosResult(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}