// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type PirkeiAvosResult_obj = {
    kind: number;
    perek1: number;
    perek2: number;
};



/**
 * Flat tagged union for Pirkei Avos (`kind`: 0 = single, 1 = combined).
 */
export class PirkeiAvosResult {
    get kind(): number;
    set kind(value: number);
    get perek1(): number;
    set perek1(value: number);
    get perek2(): number;
    set perek2(value: number);
    /** @internal */
    static fromFields(structObj : PirkeiAvosResult_obj) : PirkeiAvosResult;

    /**
    * Create `PirkeiAvosResult` from an object that contains all of `PirkeiAvosResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: PirkeiAvosResult_obj);

}