// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class SideCode {

    /** @internal */
    static fromValue(value: SideCode | string): SideCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Aleph : SideCode;
    static Bet : SideCode;


    constructor(value: SideCode | string );
}