// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class SideCode {
    #value = undefined;

    static #values = new Map([
        ["Aleph", 0],
        ["Bet", 1]
    ]);

    static getAllEntries() {
        return SideCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return SideCode.#objectValues[arguments[1]];
        }

        if (value instanceof SideCode) {
            return value;
        }

        let intVal = SideCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return SideCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a SideCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new SideCode(value);
    }

    get value(){
        return [...SideCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new SideCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new SideCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Aleph = SideCode.#objectValues[0];
    static Bet = SideCode.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}