// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Flat tagged union for Tehillim (`kind`: 0 = psalms range, 1 = verse range).
 */
export class TehillimResult {
    #kind;
    get kind() {
        return this.#kind;
    }
    set kind(value){
        this.#kind = value;
    }
    #start;
    get start() {
        return this.#start;
    }
    set start(value){
        this.#start = value;
    }
    #end;
    get end() {
        return this.#end;
    }
    set end(value){
        this.#end = value;
    }
    #psalm;
    get psalm() {
        return this.#psalm;
    }
    set psalm(value){
        this.#psalm = value;
    }
    #startVerse;
    get startVerse() {
        return this.#startVerse;
    }
    set startVerse(value){
        this.#startVerse = value;
    }
    #endVerse;
    get endVerse() {
        return this.#endVerse;
    }
    set endVerse(value){
        this.#endVerse = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new TehillimResult(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("TehillimResult's constructor takes an object of TehillimResult's fields.");
        }

        if ("kind" in structObj) {
            this.#kind = structObj.kind;
        } else {
            throw new Error("Missing required field kind.");
        }

        if ("start" in structObj) {
            this.#start = structObj.start;
        } else {
            throw new Error("Missing required field start.");
        }

        if ("end" in structObj) {
            this.#end = structObj.end;
        } else {
            throw new Error("Missing required field end.");
        }

        if ("psalm" in structObj) {
            this.#psalm = structObj.psalm;
        } else {
            throw new Error("Missing required field psalm.");
        }

        if ("startVerse" in structObj) {
            this.#startVerse = structObj.startVerse;
        } else {
            throw new Error("Missing required field startVerse.");
        }

        if ("endVerse" in structObj) {
            this.#endVerse = structObj.endVerse;
        } else {
            throw new Error("Missing required field endVerse.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 8;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 2;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof TehillimResult) {
            return obj;
        }

        return TehillimResult.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#kind, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 1, this.#start, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 2, this.#end, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 3, this.#psalm, Uint8Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#startVerse, Uint16Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 6, this.#endVerse, Uint16Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("TehillimResult._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const kindDeref = (new Uint8Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.kind = kindDeref;
        const startDeref = (new Uint8Array(wasm.memory.buffer, ptr + 1, 1))[0];
        structObj.start = startDeref;
        const endDeref = (new Uint8Array(wasm.memory.buffer, ptr + 2, 1))[0];
        structObj.end = endDeref;
        const psalmDeref = (new Uint8Array(wasm.memory.buffer, ptr + 3, 1))[0];
        structObj.psalm = psalmDeref;
        const startVerseDeref = (new Uint16Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.startVerse = startVerseDeref;
        const endVerseDeref = (new Uint16Array(wasm.memory.buffer, ptr + 6, 1))[0];
        structObj.endVerse = endVerseDeref;

        return new TehillimResult(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}