// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type TehillimResult_obj = {
    kind: number;
    start: number;
    end: number;
    psalm: number;
    startVerse: number;
    endVerse: number;
};



/**
 * Flat tagged union for Tehillim (`kind`: 0 = psalms range, 1 = verse range).
 */
export class TehillimResult {
    get kind(): number;
    set kind(value: number);
    get start(): number;
    set start(value: number);
    get end(): number;
    set end(value: number);
    get psalm(): number;
    set psalm(value: number);
    get startVerse(): number;
    set startVerse(value: number);
    get endVerse(): number;
    set endVerse(value: number);
    /** @internal */
    static fromFields(structObj : TehillimResult_obj) : TehillimResult;

    /**
    * Create `TehillimResult` from an object that contains all of `TehillimResult`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: TehillimResult_obj);

}