// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class TractateCode {

    /** @internal */
    static fromValue(value: TractateCode | string): TractateCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Berachos : TractateCode;
    static Peah : TractateCode;
    static Demai : TractateCode;
    static Kilayim : TractateCode;
    static Sheviis : TractateCode;
    static Terumos : TractateCode;
    static Maasros : TractateCode;
    static MaaserSheni : TractateCode;
    static Chalah : TractateCode;
    static Orlah : TractateCode;
    static Bikurim : TractateCode;
    static Shabbos : TractateCode;
    static Eruvin : TractateCode;
    static Pesachim : TractateCode;
    static Shekalim : TractateCode;
    static Yoma : TractateCode;
    static Sukkah : TractateCode;
    static Beitzah : TractateCode;
    static RoshHashanah : TractateCode;
    static Taanis : TractateCode;
    static Megillah : TractateCode;
    static MoedKatan : TractateCode;
    static Chagigah : TractateCode;
    static Yevamos : TractateCode;
    static Kesubos : TractateCode;
    static Nedarim : TractateCode;
    static Nazir : TractateCode;
    static Sotah : TractateCode;
    static Gitin : TractateCode;
    static Kiddushin : TractateCode;
    static BavaKamma : TractateCode;
    static BavaMetzia : TractateCode;
    static BavaBasra : TractateCode;
    static Sanhedrin : TractateCode;
    static Makkos : TractateCode;
    static Shevuos : TractateCode;
    static Eduyos : TractateCode;
    static AvodahZarah : TractateCode;
    static Avos : TractateCode;
    static Horiyos : TractateCode;
    static Zevachim : TractateCode;
    static Menachos : TractateCode;
    static Chullin : TractateCode;
    static Bechoros : TractateCode;
    static Arachin : TractateCode;
    static Temurah : TractateCode;
    static Kerisos : TractateCode;
    static Meilah : TractateCode;
    static Tamid : TractateCode;
    static Midos : TractateCode;
    static Kinnim : TractateCode;
    static Keilim : TractateCode;
    static Ohalos : TractateCode;
    static Negaim : TractateCode;
    static Parah : TractateCode;
    static Taharos : TractateCode;
    static Mikvaos : TractateCode;
    static Niddah : TractateCode;
    static Machshirin : TractateCode;
    static Zavim : TractateCode;
    static TevulYom : TractateCode;
    static Yadayim : TractateCode;
    static Uktzin : TractateCode;


    constructor(value: TractateCode | string );
}