// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class TractateCode {
    #value = undefined;

    static #values = new Map([
        ["Berachos", 0],
        ["Peah", 1],
        ["Demai", 2],
        ["Kilayim", 3],
        ["Sheviis", 4],
        ["Terumos", 5],
        ["Maasros", 6],
        ["MaaserSheni", 7],
        ["Chalah", 8],
        ["Orlah", 9],
        ["Bikurim", 10],
        ["Shabbos", 11],
        ["Eruvin", 12],
        ["Pesachim", 13],
        ["Shekalim", 14],
        ["Yoma", 15],
        ["Sukkah", 16],
        ["Beitzah", 17],
        ["RoshHashanah", 18],
        ["Taanis", 19],
        ["Megillah", 20],
        ["MoedKatan", 21],
        ["Chagigah", 22],
        ["Yevamos", 23],
        ["Kesubos", 24],
        ["Nedarim", 25],
        ["Nazir", 26],
        ["Sotah", 27],
        ["Gitin", 28],
        ["Kiddushin", 29],
        ["BavaKamma", 30],
        ["BavaMetzia", 31],
        ["BavaBasra", 32],
        ["Sanhedrin", 33],
        ["Makkos", 34],
        ["Shevuos", 35],
        ["Eduyos", 36],
        ["AvodahZarah", 37],
        ["Avos", 38],
        ["Horiyos", 39],
        ["Zevachim", 40],
        ["Menachos", 41],
        ["Chullin", 42],
        ["Bechoros", 43],
        ["Arachin", 44],
        ["Temurah", 45],
        ["Kerisos", 46],
        ["Meilah", 47],
        ["Tamid", 48],
        ["Midos", 49],
        ["Kinnim", 50],
        ["Keilim", 51],
        ["Ohalos", 52],
        ["Negaim", 53],
        ["Parah", 54],
        ["Taharos", 55],
        ["Mikvaos", 56],
        ["Niddah", 57],
        ["Machshirin", 58],
        ["Zavim", 59],
        ["TevulYom", 60],
        ["Yadayim", 61],
        ["Uktzin", 62]
    ]);

    static getAllEntries() {
        return TractateCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return TractateCode.#objectValues[arguments[1]];
        }

        if (value instanceof TractateCode) {
            return value;
        }

        let intVal = TractateCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return TractateCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a TractateCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new TractateCode(value);
    }

    get value(){
        return [...TractateCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 16),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 17),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 18),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 19),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 20),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 21),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 22),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 23),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 24),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 25),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 26),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 27),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 28),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 29),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 30),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 31),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 32),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 33),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 34),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 35),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 36),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 37),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 38),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 39),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 40),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 41),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 42),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 43),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 44),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 45),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 46),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 47),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 48),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 49),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 50),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 51),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 52),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 53),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 54),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 55),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 56),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 57),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 58),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 59),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 60),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 61),
        new TractateCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 62),
    ];

    static Berachos = TractateCode.#objectValues[0];
    static Peah = TractateCode.#objectValues[1];
    static Demai = TractateCode.#objectValues[2];
    static Kilayim = TractateCode.#objectValues[3];
    static Sheviis = TractateCode.#objectValues[4];
    static Terumos = TractateCode.#objectValues[5];
    static Maasros = TractateCode.#objectValues[6];
    static MaaserSheni = TractateCode.#objectValues[7];
    static Chalah = TractateCode.#objectValues[8];
    static Orlah = TractateCode.#objectValues[9];
    static Bikurim = TractateCode.#objectValues[10];
    static Shabbos = TractateCode.#objectValues[11];
    static Eruvin = TractateCode.#objectValues[12];
    static Pesachim = TractateCode.#objectValues[13];
    static Shekalim = TractateCode.#objectValues[14];
    static Yoma = TractateCode.#objectValues[15];
    static Sukkah = TractateCode.#objectValues[16];
    static Beitzah = TractateCode.#objectValues[17];
    static RoshHashanah = TractateCode.#objectValues[18];
    static Taanis = TractateCode.#objectValues[19];
    static Megillah = TractateCode.#objectValues[20];
    static MoedKatan = TractateCode.#objectValues[21];
    static Chagigah = TractateCode.#objectValues[22];
    static Yevamos = TractateCode.#objectValues[23];
    static Kesubos = TractateCode.#objectValues[24];
    static Nedarim = TractateCode.#objectValues[25];
    static Nazir = TractateCode.#objectValues[26];
    static Sotah = TractateCode.#objectValues[27];
    static Gitin = TractateCode.#objectValues[28];
    static Kiddushin = TractateCode.#objectValues[29];
    static BavaKamma = TractateCode.#objectValues[30];
    static BavaMetzia = TractateCode.#objectValues[31];
    static BavaBasra = TractateCode.#objectValues[32];
    static Sanhedrin = TractateCode.#objectValues[33];
    static Makkos = TractateCode.#objectValues[34];
    static Shevuos = TractateCode.#objectValues[35];
    static Eduyos = TractateCode.#objectValues[36];
    static AvodahZarah = TractateCode.#objectValues[37];
    static Avos = TractateCode.#objectValues[38];
    static Horiyos = TractateCode.#objectValues[39];
    static Zevachim = TractateCode.#objectValues[40];
    static Menachos = TractateCode.#objectValues[41];
    static Chullin = TractateCode.#objectValues[42];
    static Bechoros = TractateCode.#objectValues[43];
    static Arachin = TractateCode.#objectValues[44];
    static Temurah = TractateCode.#objectValues[45];
    static Kerisos = TractateCode.#objectValues[46];
    static Meilah = TractateCode.#objectValues[47];
    static Tamid = TractateCode.#objectValues[48];
    static Midos = TractateCode.#objectValues[49];
    static Kinnim = TractateCode.#objectValues[50];
    static Keilim = TractateCode.#objectValues[51];
    static Ohalos = TractateCode.#objectValues[52];
    static Negaim = TractateCode.#objectValues[53];
    static Parah = TractateCode.#objectValues[54];
    static Taharos = TractateCode.#objectValues[55];
    static Mikvaos = TractateCode.#objectValues[56];
    static Niddah = TractateCode.#objectValues[57];
    static Machshirin = TractateCode.#objectValues[58];
    static Zavim = TractateCode.#objectValues[59];
    static TevulYom = TractateCode.#objectValues[60];
    static Yadayim = TractateCode.#objectValues[61];
    static Uktzin = TractateCode.#objectValues[62];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}