// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class YearLengthTypeCode {

    /** @internal */
    static fromValue(value: YearLengthTypeCode | string): YearLengthTypeCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Chaserim : YearLengthTypeCode;
    static Kesidran : YearLengthTypeCode;
    static Shelaimim : YearLengthTypeCode;


    constructor(value: YearLengthTypeCode | string );
}