// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class YearLengthTypeCode {
    #value = undefined;

    static #values = new Map([
        ["Chaserim", 0],
        ["Kesidran", 1],
        ["Shelaimim", 2]
    ]);

    static getAllEntries() {
        return YearLengthTypeCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return YearLengthTypeCode.#objectValues[arguments[1]];
        }

        if (value instanceof YearLengthTypeCode) {
            return value;
        }

        let intVal = YearLengthTypeCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return YearLengthTypeCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a YearLengthTypeCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new YearLengthTypeCode(value);
    }

    get value(){
        return [...YearLengthTypeCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new YearLengthTypeCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new YearLengthTypeCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new YearLengthTypeCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
    ];

    static Chaserim = YearLengthTypeCode.#objectValues[0];
    static Kesidran = YearLengthTypeCode.#objectValues[1];
    static Shelaimim = YearLengthTypeCode.#objectValues[2];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}