// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Stable identifier for a generated zman preset.
 */
export class ZmanPresetId {
    #value = undefined;

    static #values = new Map([
        ["Alos120Minutes", 0],
        ["Alos120Zmanis", 1],
        ["Alos16Point1Degrees", 2],
        ["Alos18Degrees", 3],
        ["Alos19Degrees", 4],
        ["Alos19Point8Degrees", 5],
        ["Alos26Degrees", 6],
        ["Alos60Minutes", 7],
        ["Alos72Minutes", 8],
        ["Alos72Zmanis", 9],
        ["Alos90Minutes", 10],
        ["Alos90Zmanis", 11],
        ["Alos96Minutes", 12],
        ["Alos96Zmanis", 13],
        ["AlosBaalHatanya", 14],
        ["BainHashmashosRt13Point24Degrees", 15],
        ["BainHashmashosRt13Point5MinutesBefore7Point083Degrees", 16],
        ["BainHashmashosRt2Stars", 17],
        ["BainHashmashosRt58Point5Minutes", 18],
        ["BainHashmashosYereim13Point5Minutes", 19],
        ["BainHashmashosYereim16Point875Minutes", 20],
        ["BainHashmashosYereim18Minutes", 21],
        ["BainHashmashosYereim2Point1Degrees", 22],
        ["BainHashmashosYereim2Point8Degrees", 23],
        ["BainHashmashosYereim3Point05Degrees", 24],
        ["BeginAstronomicalTwilight", 25],
        ["BeginCivilTwilight", 26],
        ["BeginNauticalTwilight", 27],
        ["CandleLighting", 28],
        ["ChatzosHalayla", 29],
        ["ChatzosHayom", 30],
        ["ChatzosHayomAsHalfDay", 31],
        ["ElevationAdjustedSunrise", 32],
        ["ElevationAdjustedSunset", 33],
        ["EndAstronomicalTwilight", 34],
        ["EndCivilTwilight", 35],
        ["EndNauticalTwilight", 36],
        ["FixedLocalChatzosHayom", 37],
        ["MinchaGedola16Point1Degrees", 38],
        ["MinchaGedola30Minutes", 39],
        ["MinchaGedola72Minutes", 40],
        ["MinchaGedolaAhavatShalom", 41],
        ["MinchaGedolaAteretTorah", 42],
        ["MinchaGedolaBaalHatanya", 43],
        ["MinchaGedolaGra", 44],
        ["MinchaGedolaGrafixedLocalChatzos30Minutes", 45],
        ["MinchaGedolaGragreaterThan30", 46],
        ["MinchaKetana16Point1Degrees", 47],
        ["MinchaKetana72Minutes", 48],
        ["MinchaKetanaAhavatShalom", 49],
        ["MinchaKetanaAteretTorah", 50],
        ["MinchaKetanaBaalHatanya", 51],
        ["MinchaKetanaGra", 52],
        ["MinchaKetanaGrafixedLocalChatzosToSunset", 53],
        ["Misheyakir10Point2Degrees", 54],
        ["Misheyakir11Degrees", 55],
        ["Misheyakir11Point5Degrees", 56],
        ["Misheyakir12Point85Degrees", 57],
        ["Misheyakir7Point65Degrees", 58],
        ["Misheyakir9Point5Degrees", 59],
        ["PlagAhavatShalom", 60],
        ["PlagAlos16Point1DegreesToTzaisGeonim7Point083Degrees", 61],
        ["PlagAlosToSunset", 62],
        ["PlagHamincha120Minutes", 63],
        ["PlagHamincha120MinutesZmanis", 64],
        ["PlagHamincha16Point1Degrees", 65],
        ["PlagHamincha18Degrees", 66],
        ["PlagHamincha19Point8Degrees", 67],
        ["PlagHamincha26Degrees", 68],
        ["PlagHamincha60Minutes", 69],
        ["PlagHamincha72Minutes", 70],
        ["PlagHamincha72MinutesZmanis", 71],
        ["PlagHamincha90Minutes", 72],
        ["PlagHamincha90MinutesZmanis", 73],
        ["PlagHamincha96Minutes", 74],
        ["PlagHamincha96MinutesZmanis", 75],
        ["PlagHaminchaAteretTorah", 76],
        ["PlagHaminchaBaalHatanya", 77],
        ["PlagHaminchaGra", 78],
        ["PlagHaminchaGrafixedLocalChatzosToSunset", 79],
        ["PolarSunriseBenIshChai", 80],
        ["PolarSunsetBenIshChai", 81],
        ["SamuchLeMinchaKetana16Point1Degrees", 82],
        ["SamuchLeMinchaKetana72Minutes", 83],
        ["SamuchLeMinchaKetanaGra", 84],
        ["SeaLevelSunrise", 85],
        ["SeaLevelSunset", 86],
        ["SofZmanAchilasChametzBaalHatanya", 87],
        ["SofZmanAchilasChametzGra", 88],
        ["SofZmanAchilasChametzMga16Point1Degrees", 89],
        ["SofZmanAchilasChametzMga72Minutes", 90],
        ["SofZmanAchilasChametzMga72MinutesZmanis", 91],
        ["SofZmanBiurChametzBaalHatanya", 92],
        ["SofZmanBiurChametzGra", 93],
        ["SofZmanBiurChametzMga16Point1Degrees", 94],
        ["SofZmanBiurChametzMga72Minutes", 95],
        ["SofZmanBiurChametzMga72MinutesZmanis", 96],
        ["SofZmanKidushLevana15Days", 97],
        ["SofZmanKidushLevanaBetweenMoldos", 98],
        ["SofZmanShma3HoursBeforeChatzos", 99],
        ["SofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees", 100],
        ["SofZmanShmaAlos16Point1ToSunset", 101],
        ["SofZmanShmaAteretTorah", 102],
        ["SofZmanShmaBaalHatanya", 103],
        ["SofZmanShmaGra", 104],
        ["SofZmanShmaGrasunriseToFixedLocalChatzos", 105],
        ["SofZmanShmaMga120Minutes", 106],
        ["SofZmanShmaMga16Point1Degrees", 107],
        ["SofZmanShmaMga16Point1DegreesToFixedLocalChatzos", 108],
        ["SofZmanShmaMga18Degrees", 109],
        ["SofZmanShmaMga18DegreesToFixedLocalChatzos", 110],
        ["SofZmanShmaMga19Point8Degrees", 111],
        ["SofZmanShmaMga72Minutes", 112],
        ["SofZmanShmaMga72MinutesToFixedLocalChatzos", 113],
        ["SofZmanShmaMga72MinutesZmanis", 114],
        ["SofZmanShmaMga90Minutes", 115],
        ["SofZmanShmaMga90MinutesToFixedLocalChatzos", 116],
        ["SofZmanShmaMga90MinutesZmanis", 117],
        ["SofZmanShmaMga96Minutes", 118],
        ["SofZmanShmaMga96MinutesZmanis", 119],
        ["SofZmanTfila2HoursBeforeChatzos", 120],
        ["SofZmanTfilaAteretTorah", 121],
        ["SofZmanTfilaBaalHatanya", 122],
        ["SofZmanTfilaGra", 123],
        ["SofZmanTfilaGrasunriseToFixedLocalChatzos", 124],
        ["SofZmanTfilaMga120Minutes", 125],
        ["SofZmanTfilaMga16Point1Degrees", 126],
        ["SofZmanTfilaMga18Degrees", 127],
        ["SofZmanTfilaMga19Point8Degrees", 128],
        ["SofZmanTfilaMga72Minutes", 129],
        ["SofZmanTfilaMga72MinutesZmanis", 130],
        ["SofZmanTfilaMga90Minutes", 131],
        ["SofZmanTfilaMga90MinutesZmanis", 132],
        ["SofZmanTfilaMga96Minutes", 133],
        ["SofZmanTfilaMga96MinutesZmanis", 134],
        ["SolarMidnight", 135],
        ["SunTransit", 136],
        ["TchilasZmanKidushLevana3Days", 137],
        ["TchilasZmanKidushLevana7Days", 138],
        ["Tzais120Minutes", 139],
        ["Tzais120Zmanis", 140],
        ["Tzais16Point1Degrees", 141],
        ["Tzais18Degrees", 142],
        ["Tzais19Point8Degrees", 143],
        ["Tzais26Degrees", 144],
        ["Tzais50Minutes", 145],
        ["Tzais60Minutes", 146],
        ["Tzais72Minutes", 147],
        ["Tzais72Zmanis", 148],
        ["Tzais90Minutes", 149],
        ["Tzais90Zmanis", 150],
        ["Tzais96Minutes", 151],
        ["Tzais96Zmanis", 152],
        ["TzaisAteretTorah", 153],
        ["TzaisBaalHatanya", 154],
        ["TzaisGeonim3Point7Degrees", 155],
        ["TzaisGeonim3Point8Degrees", 156],
        ["TzaisGeonim4Point42Degrees", 157],
        ["TzaisGeonim4Point66Degrees", 158],
        ["TzaisGeonim4Point8Degrees", 159],
        ["TzaisGeonim5Point95Degrees", 160],
        ["TzaisGeonim6Point45Degrees", 161],
        ["TzaisGeonim7Point083Degrees", 162],
        ["TzaisGeonim7Point67Degrees", 163],
        ["TzaisGeonim8Point5Degrees", 164],
        ["TzaisGeonim9Point3Degrees", 165],
        ["TzaisGeonim9Point75Degrees", 166]
    ]);

    static getAllEntries() {
        return ZmanPresetId.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return ZmanPresetId.#objectValues[arguments[1]];
        }

        if (value instanceof ZmanPresetId) {
            return value;
        }

        let intVal = ZmanPresetId.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return ZmanPresetId.#objectValues[intVal];
        }

        throw TypeError(value + " is not a ZmanPresetId and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new ZmanPresetId(value);
    }

    get value(){
        return [...ZmanPresetId.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 16),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 17),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 18),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 19),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 20),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 21),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 22),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 23),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 24),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 25),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 26),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 27),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 28),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 29),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 30),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 31),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 32),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 33),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 34),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 35),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 36),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 37),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 38),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 39),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 40),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 41),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 42),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 43),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 44),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 45),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 46),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 47),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 48),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 49),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 50),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 51),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 52),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 53),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 54),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 55),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 56),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 57),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 58),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 59),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 60),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 61),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 62),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 63),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 64),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 65),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 66),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 67),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 68),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 69),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 70),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 71),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 72),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 73),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 74),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 75),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 76),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 77),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 78),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 79),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 80),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 81),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 82),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 83),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 84),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 85),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 86),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 87),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 88),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 89),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 90),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 91),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 92),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 93),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 94),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 95),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 96),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 97),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 98),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 99),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 100),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 101),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 102),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 103),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 104),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 105),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 106),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 107),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 108),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 109),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 110),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 111),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 112),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 113),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 114),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 115),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 116),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 117),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 118),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 119),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 120),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 121),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 122),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 123),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 124),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 125),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 126),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 127),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 128),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 129),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 130),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 131),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 132),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 133),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 134),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 135),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 136),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 137),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 138),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 139),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 140),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 141),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 142),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 143),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 144),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 145),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 146),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 147),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 148),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 149),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 150),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 151),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 152),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 153),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 154),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 155),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 156),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 157),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 158),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 159),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 160),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 161),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 162),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 163),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 164),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 165),
        new ZmanPresetId(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 166),
    ];

    static Alos120Minutes = ZmanPresetId.#objectValues[0];
    static Alos120Zmanis = ZmanPresetId.#objectValues[1];
    static Alos16Point1Degrees = ZmanPresetId.#objectValues[2];
    static Alos18Degrees = ZmanPresetId.#objectValues[3];
    static Alos19Degrees = ZmanPresetId.#objectValues[4];
    static Alos19Point8Degrees = ZmanPresetId.#objectValues[5];
    static Alos26Degrees = ZmanPresetId.#objectValues[6];
    static Alos60Minutes = ZmanPresetId.#objectValues[7];
    static Alos72Minutes = ZmanPresetId.#objectValues[8];
    static Alos72Zmanis = ZmanPresetId.#objectValues[9];
    static Alos90Minutes = ZmanPresetId.#objectValues[10];
    static Alos90Zmanis = ZmanPresetId.#objectValues[11];
    static Alos96Minutes = ZmanPresetId.#objectValues[12];
    static Alos96Zmanis = ZmanPresetId.#objectValues[13];
    static AlosBaalHatanya = ZmanPresetId.#objectValues[14];
    static BainHashmashosRt13Point24Degrees = ZmanPresetId.#objectValues[15];
    static BainHashmashosRt13Point5MinutesBefore7Point083Degrees = ZmanPresetId.#objectValues[16];
    static BainHashmashosRt2Stars = ZmanPresetId.#objectValues[17];
    static BainHashmashosRt58Point5Minutes = ZmanPresetId.#objectValues[18];
    static BainHashmashosYereim13Point5Minutes = ZmanPresetId.#objectValues[19];
    static BainHashmashosYereim16Point875Minutes = ZmanPresetId.#objectValues[20];
    static BainHashmashosYereim18Minutes = ZmanPresetId.#objectValues[21];
    static BainHashmashosYereim2Point1Degrees = ZmanPresetId.#objectValues[22];
    static BainHashmashosYereim2Point8Degrees = ZmanPresetId.#objectValues[23];
    static BainHashmashosYereim3Point05Degrees = ZmanPresetId.#objectValues[24];
    static BeginAstronomicalTwilight = ZmanPresetId.#objectValues[25];
    static BeginCivilTwilight = ZmanPresetId.#objectValues[26];
    static BeginNauticalTwilight = ZmanPresetId.#objectValues[27];
    static CandleLighting = ZmanPresetId.#objectValues[28];
    static ChatzosHalayla = ZmanPresetId.#objectValues[29];
    static ChatzosHayom = ZmanPresetId.#objectValues[30];
    static ChatzosHayomAsHalfDay = ZmanPresetId.#objectValues[31];
    static ElevationAdjustedSunrise = ZmanPresetId.#objectValues[32];
    static ElevationAdjustedSunset = ZmanPresetId.#objectValues[33];
    static EndAstronomicalTwilight = ZmanPresetId.#objectValues[34];
    static EndCivilTwilight = ZmanPresetId.#objectValues[35];
    static EndNauticalTwilight = ZmanPresetId.#objectValues[36];
    static FixedLocalChatzosHayom = ZmanPresetId.#objectValues[37];
    static MinchaGedola16Point1Degrees = ZmanPresetId.#objectValues[38];
    static MinchaGedola30Minutes = ZmanPresetId.#objectValues[39];
    static MinchaGedola72Minutes = ZmanPresetId.#objectValues[40];
    static MinchaGedolaAhavatShalom = ZmanPresetId.#objectValues[41];
    static MinchaGedolaAteretTorah = ZmanPresetId.#objectValues[42];
    static MinchaGedolaBaalHatanya = ZmanPresetId.#objectValues[43];
    static MinchaGedolaGra = ZmanPresetId.#objectValues[44];
    static MinchaGedolaGrafixedLocalChatzos30Minutes = ZmanPresetId.#objectValues[45];
    static MinchaGedolaGragreaterThan30 = ZmanPresetId.#objectValues[46];
    static MinchaKetana16Point1Degrees = ZmanPresetId.#objectValues[47];
    static MinchaKetana72Minutes = ZmanPresetId.#objectValues[48];
    static MinchaKetanaAhavatShalom = ZmanPresetId.#objectValues[49];
    static MinchaKetanaAteretTorah = ZmanPresetId.#objectValues[50];
    static MinchaKetanaBaalHatanya = ZmanPresetId.#objectValues[51];
    static MinchaKetanaGra = ZmanPresetId.#objectValues[52];
    static MinchaKetanaGrafixedLocalChatzosToSunset = ZmanPresetId.#objectValues[53];
    static Misheyakir10Point2Degrees = ZmanPresetId.#objectValues[54];
    static Misheyakir11Degrees = ZmanPresetId.#objectValues[55];
    static Misheyakir11Point5Degrees = ZmanPresetId.#objectValues[56];
    static Misheyakir12Point85Degrees = ZmanPresetId.#objectValues[57];
    static Misheyakir7Point65Degrees = ZmanPresetId.#objectValues[58];
    static Misheyakir9Point5Degrees = ZmanPresetId.#objectValues[59];
    static PlagAhavatShalom = ZmanPresetId.#objectValues[60];
    static PlagAlos16Point1DegreesToTzaisGeonim7Point083Degrees = ZmanPresetId.#objectValues[61];
    static PlagAlosToSunset = ZmanPresetId.#objectValues[62];
    static PlagHamincha120Minutes = ZmanPresetId.#objectValues[63];
    static PlagHamincha120MinutesZmanis = ZmanPresetId.#objectValues[64];
    static PlagHamincha16Point1Degrees = ZmanPresetId.#objectValues[65];
    static PlagHamincha18Degrees = ZmanPresetId.#objectValues[66];
    static PlagHamincha19Point8Degrees = ZmanPresetId.#objectValues[67];
    static PlagHamincha26Degrees = ZmanPresetId.#objectValues[68];
    static PlagHamincha60Minutes = ZmanPresetId.#objectValues[69];
    static PlagHamincha72Minutes = ZmanPresetId.#objectValues[70];
    static PlagHamincha72MinutesZmanis = ZmanPresetId.#objectValues[71];
    static PlagHamincha90Minutes = ZmanPresetId.#objectValues[72];
    static PlagHamincha90MinutesZmanis = ZmanPresetId.#objectValues[73];
    static PlagHamincha96Minutes = ZmanPresetId.#objectValues[74];
    static PlagHamincha96MinutesZmanis = ZmanPresetId.#objectValues[75];
    static PlagHaminchaAteretTorah = ZmanPresetId.#objectValues[76];
    static PlagHaminchaBaalHatanya = ZmanPresetId.#objectValues[77];
    static PlagHaminchaGra = ZmanPresetId.#objectValues[78];
    static PlagHaminchaGrafixedLocalChatzosToSunset = ZmanPresetId.#objectValues[79];
    static PolarSunriseBenIshChai = ZmanPresetId.#objectValues[80];
    static PolarSunsetBenIshChai = ZmanPresetId.#objectValues[81];
    static SamuchLeMinchaKetana16Point1Degrees = ZmanPresetId.#objectValues[82];
    static SamuchLeMinchaKetana72Minutes = ZmanPresetId.#objectValues[83];
    static SamuchLeMinchaKetanaGra = ZmanPresetId.#objectValues[84];
    static SeaLevelSunrise = ZmanPresetId.#objectValues[85];
    static SeaLevelSunset = ZmanPresetId.#objectValues[86];
    static SofZmanAchilasChametzBaalHatanya = ZmanPresetId.#objectValues[87];
    static SofZmanAchilasChametzGra = ZmanPresetId.#objectValues[88];
    static SofZmanAchilasChametzMga16Point1Degrees = ZmanPresetId.#objectValues[89];
    static SofZmanAchilasChametzMga72Minutes = ZmanPresetId.#objectValues[90];
    static SofZmanAchilasChametzMga72MinutesZmanis = ZmanPresetId.#objectValues[91];
    static SofZmanBiurChametzBaalHatanya = ZmanPresetId.#objectValues[92];
    static SofZmanBiurChametzGra = ZmanPresetId.#objectValues[93];
    static SofZmanBiurChametzMga16Point1Degrees = ZmanPresetId.#objectValues[94];
    static SofZmanBiurChametzMga72Minutes = ZmanPresetId.#objectValues[95];
    static SofZmanBiurChametzMga72MinutesZmanis = ZmanPresetId.#objectValues[96];
    static SofZmanKidushLevana15Days = ZmanPresetId.#objectValues[97];
    static SofZmanKidushLevanaBetweenMoldos = ZmanPresetId.#objectValues[98];
    static SofZmanShma3HoursBeforeChatzos = ZmanPresetId.#objectValues[99];
    static SofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees = ZmanPresetId.#objectValues[100];
    static SofZmanShmaAlos16Point1ToSunset = ZmanPresetId.#objectValues[101];
    static SofZmanShmaAteretTorah = ZmanPresetId.#objectValues[102];
    static SofZmanShmaBaalHatanya = ZmanPresetId.#objectValues[103];
    static SofZmanShmaGra = ZmanPresetId.#objectValues[104];
    static SofZmanShmaGrasunriseToFixedLocalChatzos = ZmanPresetId.#objectValues[105];
    static SofZmanShmaMga120Minutes = ZmanPresetId.#objectValues[106];
    static SofZmanShmaMga16Point1Degrees = ZmanPresetId.#objectValues[107];
    static SofZmanShmaMga16Point1DegreesToFixedLocalChatzos = ZmanPresetId.#objectValues[108];
    static SofZmanShmaMga18Degrees = ZmanPresetId.#objectValues[109];
    static SofZmanShmaMga18DegreesToFixedLocalChatzos = ZmanPresetId.#objectValues[110];
    static SofZmanShmaMga19Point8Degrees = ZmanPresetId.#objectValues[111];
    static SofZmanShmaMga72Minutes = ZmanPresetId.#objectValues[112];
    static SofZmanShmaMga72MinutesToFixedLocalChatzos = ZmanPresetId.#objectValues[113];
    static SofZmanShmaMga72MinutesZmanis = ZmanPresetId.#objectValues[114];
    static SofZmanShmaMga90Minutes = ZmanPresetId.#objectValues[115];
    static SofZmanShmaMga90MinutesToFixedLocalChatzos = ZmanPresetId.#objectValues[116];
    static SofZmanShmaMga90MinutesZmanis = ZmanPresetId.#objectValues[117];
    static SofZmanShmaMga96Minutes = ZmanPresetId.#objectValues[118];
    static SofZmanShmaMga96MinutesZmanis = ZmanPresetId.#objectValues[119];
    static SofZmanTfila2HoursBeforeChatzos = ZmanPresetId.#objectValues[120];
    static SofZmanTfilaAteretTorah = ZmanPresetId.#objectValues[121];
    static SofZmanTfilaBaalHatanya = ZmanPresetId.#objectValues[122];
    static SofZmanTfilaGra = ZmanPresetId.#objectValues[123];
    static SofZmanTfilaGrasunriseToFixedLocalChatzos = ZmanPresetId.#objectValues[124];
    static SofZmanTfilaMga120Minutes = ZmanPresetId.#objectValues[125];
    static SofZmanTfilaMga16Point1Degrees = ZmanPresetId.#objectValues[126];
    static SofZmanTfilaMga18Degrees = ZmanPresetId.#objectValues[127];
    static SofZmanTfilaMga19Point8Degrees = ZmanPresetId.#objectValues[128];
    static SofZmanTfilaMga72Minutes = ZmanPresetId.#objectValues[129];
    static SofZmanTfilaMga72MinutesZmanis = ZmanPresetId.#objectValues[130];
    static SofZmanTfilaMga90Minutes = ZmanPresetId.#objectValues[131];
    static SofZmanTfilaMga90MinutesZmanis = ZmanPresetId.#objectValues[132];
    static SofZmanTfilaMga96Minutes = ZmanPresetId.#objectValues[133];
    static SofZmanTfilaMga96MinutesZmanis = ZmanPresetId.#objectValues[134];
    static SolarMidnight = ZmanPresetId.#objectValues[135];
    static SunTransit = ZmanPresetId.#objectValues[136];
    static TchilasZmanKidushLevana3Days = ZmanPresetId.#objectValues[137];
    static TchilasZmanKidushLevana7Days = ZmanPresetId.#objectValues[138];
    static Tzais120Minutes = ZmanPresetId.#objectValues[139];
    static Tzais120Zmanis = ZmanPresetId.#objectValues[140];
    static Tzais16Point1Degrees = ZmanPresetId.#objectValues[141];
    static Tzais18Degrees = ZmanPresetId.#objectValues[142];
    static Tzais19Point8Degrees = ZmanPresetId.#objectValues[143];
    static Tzais26Degrees = ZmanPresetId.#objectValues[144];
    static Tzais50Minutes = ZmanPresetId.#objectValues[145];
    static Tzais60Minutes = ZmanPresetId.#objectValues[146];
    static Tzais72Minutes = ZmanPresetId.#objectValues[147];
    static Tzais72Zmanis = ZmanPresetId.#objectValues[148];
    static Tzais90Minutes = ZmanPresetId.#objectValues[149];
    static Tzais90Zmanis = ZmanPresetId.#objectValues[150];
    static Tzais96Minutes = ZmanPresetId.#objectValues[151];
    static Tzais96Zmanis = ZmanPresetId.#objectValues[152];
    static TzaisAteretTorah = ZmanPresetId.#objectValues[153];
    static TzaisBaalHatanya = ZmanPresetId.#objectValues[154];
    static TzaisGeonim3Point7Degrees = ZmanPresetId.#objectValues[155];
    static TzaisGeonim3Point8Degrees = ZmanPresetId.#objectValues[156];
    static TzaisGeonim4Point42Degrees = ZmanPresetId.#objectValues[157];
    static TzaisGeonim4Point66Degrees = ZmanPresetId.#objectValues[158];
    static TzaisGeonim4Point8Degrees = ZmanPresetId.#objectValues[159];
    static TzaisGeonim5Point95Degrees = ZmanPresetId.#objectValues[160];
    static TzaisGeonim6Point45Degrees = ZmanPresetId.#objectValues[161];
    static TzaisGeonim7Point083Degrees = ZmanPresetId.#objectValues[162];
    static TzaisGeonim7Point67Degrees = ZmanPresetId.#objectValues[163];
    static TzaisGeonim8Point5Degrees = ZmanPresetId.#objectValues[164];
    static TzaisGeonim9Point3Degrees = ZmanPresetId.#objectValues[165];
    static TzaisGeonim9Point75Degrees = ZmanPresetId.#objectValues[166];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}