// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ZmanimErrorCode {

    /** @internal */
    static fromValue(value: ZmanimErrorCode | string): ZmanimErrorCode;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static InvalidLatitude : ZmanimErrorCode;
    static InvalidLongitude : ZmanimErrorCode;
    static InvalidElevation : ZmanimErrorCode;
    static TimeZoneRequired : ZmanimErrorCode;
    static CalculationError : ZmanimErrorCode;
    static AllDay : ZmanimErrorCode;
    static AllNight : ZmanimErrorCode;
    static TimeConversionError : ZmanimErrorCode;
    static InvalidForDate : ZmanimErrorCode;
    static InvalidHours : ZmanimErrorCode;


    constructor(value: ZmanimErrorCode | string );
}