// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



export class ZmanimErrorCode {
    #value = undefined;

    static #values = new Map([
        ["InvalidLatitude", 0],
        ["InvalidLongitude", 1],
        ["InvalidElevation", 2],
        ["TimeZoneRequired", 3],
        ["CalculationError", 4],
        ["AllDay", 5],
        ["AllNight", 6],
        ["TimeConversionError", 7],
        ["InvalidForDate", 8],
        ["InvalidHours", 9]
    ]);

    static getAllEntries() {
        return ZmanimErrorCode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return ZmanimErrorCode.#objectValues[arguments[1]];
        }

        if (value instanceof ZmanimErrorCode) {
            return value;
        }

        let intVal = ZmanimErrorCode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return ZmanimErrorCode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a ZmanimErrorCode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new ZmanimErrorCode(value);
    }

    get value(){
        return [...ZmanimErrorCode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new ZmanimErrorCode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
    ];

    static InvalidLatitude = ZmanimErrorCode.#objectValues[0];
    static InvalidLongitude = ZmanimErrorCode.#objectValues[1];
    static InvalidElevation = ZmanimErrorCode.#objectValues[2];
    static TimeZoneRequired = ZmanimErrorCode.#objectValues[3];
    static CalculationError = ZmanimErrorCode.#objectValues[4];
    static AllDay = ZmanimErrorCode.#objectValues[5];
    static AllNight = ZmanimErrorCode.#objectValues[6];
    static TimeConversionError = ZmanimErrorCode.#objectValues[7];
    static InvalidForDate = ZmanimErrorCode.#objectValues[8];
    static InvalidHours = ZmanimErrorCode.#objectValues[9];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}