// generated by diplomat-tool
import type { ZmanPresetId } from "./ZmanPresetId"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Dart entry point: construct once and call instance methods.
 */
export class ZmanPresets {
    /** @internal */
    get ffiValue(): pointer;


    presetCount(): number;

    presetName(preset: ZmanPresetId): boolean;

    presetDeprecated(preset: ZmanPresetId): boolean;

    presetMethodName(preset: ZmanPresetId): boolean;

    constructor();
}