// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1805115147;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__ZmanimPreset_name_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ZmanimPreset_name",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::ZmanimPreset::name(&*api_that_guard))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__add_days_to_jewish_date_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "add_days_to_jewish_date",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            let api_days_to_add = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::add_days_to_jewish_date(
                    api_year,
                    api_month,
                    api_day,
                    api_days_to_add,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__add_months_to_jewish_date_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "add_months_to_jewish_date",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            let api_months_to_add = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::add_months_to_jewish_date(
                    api_year,
                    api_month,
                    api_day,
                    api_months_to_add,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__add_years_to_jewish_date_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "add_years_to_jewish_date",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            let api_years_to_add = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::add_years_to_jewish_date(
                    api_year,
                    api_month,
                    api_day,
                    api_years_to_add,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__calculate_zman_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_zman",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_ateret_torah_sunset_offset_minutes = <i64>::sse_decode(&mut deserializer);
            let api_candle_lighting_offset_minutes = <i64>::sse_decode(&mut deserializer);
            let api_use_astronomical_chatzos_for_other_zmanim =
                <bool>::sse_decode(&mut deserializer);
            let api_latitude = <f64>::sse_decode(&mut deserializer);
            let api_longitude = <f64>::sse_decode(&mut deserializer);
            let api_elevation = <f64>::sse_decode(&mut deserializer);
            let api_timezone = <String>::sse_decode(&mut deserializer);
            let api_random_year = <i64>::sse_decode(&mut deserializer);
            let api_random_month = <i64>::sse_decode(&mut deserializer);
            let api_random_day = <i64>::sse_decode(&mut deserializer);
            let api_use_elevation = <bool>::sse_decode(&mut deserializer);
            let api_zman = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_zman_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_zman, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_zman_guard = Some(api_zman.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_zman_guard = api_zman_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok(crate::api::calculate_zman(
                    api_ateret_torah_sunset_offset_minutes,
                    api_candle_lighting_offset_minutes,
                    api_use_astronomical_chatzos_for_other_zmanim,
                    api_latitude,
                    api_longitude,
                    api_elevation,
                    api_timezone,
                    api_random_year,
                    api_random_month,
                    api_random_day,
                    api_use_elevation,
                    &*api_zman_guard,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__find_timezone_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "find_timezone",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_longitude = <f64>::sse_decode(&mut deserializer);
            let api_latitude = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::find_timezone(api_longitude, api_latitude))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__gregorian_date_to_jewish_date_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "gregorian_date_to_jewish_date",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::gregorian_date_to_jewish_date(
                    api_year, api_month, api_day,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__java_jewish_calendar_test_results_new_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "java_jewish_calendar_test_results_new",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_isUseModernHolidays = <bool>::sse_decode(&mut deserializer);
            let api_getInIsrael = <bool>::sse_decode(&mut deserializer);
            let api_getIsMukafChoma = <bool>::sse_decode(&mut deserializer);
            let api_isBirkasHachamah = <bool>::sse_decode(&mut deserializer);
            let api_getParshah = <Option<i32>>::sse_decode(&mut deserializer);
            let api_getUpcomingParshah = <i32>::sse_decode(&mut deserializer);
            let api_getSpecialShabbos = <Option<i32>>::sse_decode(&mut deserializer);
            let api_getYomTovIndex = <i32>::sse_decode(&mut deserializer);
            let api_isYomTov = <bool>::sse_decode(&mut deserializer);
            let api_isYomTovAssurBemelacha = <bool>::sse_decode(&mut deserializer);
            let api_isAssurBemelacha = <bool>::sse_decode(&mut deserializer);
            let api_hasCandleLighting = <bool>::sse_decode(&mut deserializer);
            let api_isTomorrowShabbosOrYomTov = <bool>::sse_decode(&mut deserializer);
            let api_isErevYomTovSheni = <bool>::sse_decode(&mut deserializer);
            let api_isAseresYemeiTeshuva = <bool>::sse_decode(&mut deserializer);
            let api_isPesach = <bool>::sse_decode(&mut deserializer);
            let api_isCholHamoedPesach = <bool>::sse_decode(&mut deserializer);
            let api_isShavuos = <bool>::sse_decode(&mut deserializer);
            let api_isRoshHashana = <bool>::sse_decode(&mut deserializer);
            let api_isYomKippur = <bool>::sse_decode(&mut deserializer);
            let api_isSuccos = <bool>::sse_decode(&mut deserializer);
            let api_isHoshanaRabba = <bool>::sse_decode(&mut deserializer);
            let api_isShminiAtzeres = <bool>::sse_decode(&mut deserializer);
            let api_isSimchasTorah = <bool>::sse_decode(&mut deserializer);
            let api_isCholHamoedSuccos = <bool>::sse_decode(&mut deserializer);
            let api_isCholHamoed = <bool>::sse_decode(&mut deserializer);
            let api_isErevYomTov = <bool>::sse_decode(&mut deserializer);
            let api_isErevRoshChodesh = <bool>::sse_decode(&mut deserializer);
            let api_isYomKippurKatan = <bool>::sse_decode(&mut deserializer);
            let api_isBeHaB = <bool>::sse_decode(&mut deserializer);
            let api_isTaanis = <bool>::sse_decode(&mut deserializer);
            let api_isTaanisBechoros = <bool>::sse_decode(&mut deserializer);
            let api_getDayOfChanukah = <Option<u8>>::sse_decode(&mut deserializer);
            let api_isChanukah = <bool>::sse_decode(&mut deserializer);
            let api_isPurim = <bool>::sse_decode(&mut deserializer);
            let api_isRoshChodesh = <bool>::sse_decode(&mut deserializer);
            let api_isMacharChodesh = <bool>::sse_decode(&mut deserializer);
            let api_isShabbosMevorchim = <bool>::sse_decode(&mut deserializer);
            let api_getDayOfOmer = <Option<u8>>::sse_decode(&mut deserializer);
            let api_isTishaBav = <bool>::sse_decode(&mut deserializer);
            let api_getMoladAsInstant = <i64>::sse_decode(&mut deserializer);
            let api_getTchilasZmanKidushLevana3Days = <i64>::sse_decode(&mut deserializer);
            let api_getTchilasZmanKidushLevana7Days = <i64>::sse_decode(&mut deserializer);
            let api_getSofZmanKidushLevanaBetweenMoldos = <i64>::sse_decode(&mut deserializer);
            let api_getSofZmanKidushLevana15Days = <i64>::sse_decode(&mut deserializer);
            let api_getTekufasTishreiElapsedDays = <i32>::sse_decode(&mut deserializer);
            let api_isIsruChag = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::JavaJewishCalendarTestResults::new(
                        api_isUseModernHolidays,
                        api_getInIsrael,
                        api_getIsMukafChoma,
                        api_isBirkasHachamah,
                        api_getParshah,
                        api_getUpcomingParshah,
                        api_getSpecialShabbos,
                        api_getYomTovIndex,
                        api_isYomTov,
                        api_isYomTovAssurBemelacha,
                        api_isAssurBemelacha,
                        api_hasCandleLighting,
                        api_isTomorrowShabbosOrYomTov,
                        api_isErevYomTovSheni,
                        api_isAseresYemeiTeshuva,
                        api_isPesach,
                        api_isCholHamoedPesach,
                        api_isShavuos,
                        api_isRoshHashana,
                        api_isYomKippur,
                        api_isSuccos,
                        api_isHoshanaRabba,
                        api_isShminiAtzeres,
                        api_isSimchasTorah,
                        api_isCholHamoedSuccos,
                        api_isCholHamoed,
                        api_isErevYomTov,
                        api_isErevRoshChodesh,
                        api_isYomKippurKatan,
                        api_isBeHaB,
                        api_isTaanis,
                        api_isTaanisBechoros,
                        api_getDayOfChanukah,
                        api_isChanukah,
                        api_isPurim,
                        api_isRoshChodesh,
                        api_isMacharChodesh,
                        api_isShabbosMevorchim,
                        api_getDayOfOmer,
                        api_isTishaBav,
                        api_getMoladAsInstant,
                        api_getTchilasZmanKidushLevana3Days,
                        api_getTchilasZmanKidushLevana7Days,
                        api_getSofZmanKidushLevanaBetweenMoldos,
                        api_getSofZmanKidushLevana15Days,
                        api_getTekufasTishreiElapsedDays,
                        api_isIsruChag,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__jewish_date_to_gregorian_date_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "jewish_date_to_gregorian_date",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::jewish_date_to_gregorian_date(
                    api_year, api_month, api_day,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__presets_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "presets",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::presets())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__test_jewish_calendar_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "test_jewish_calendar",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_year = <i32>::sse_decode(&mut deserializer);
            let api_month = <u8>::sse_decode(&mut deserializer);
            let api_day = <u8>::sse_decode(&mut deserializer);
            let api_in_israel = <bool>::sse_decode(&mut deserializer);
            let api_is_mukaf_choma = <bool>::sse_decode(&mut deserializer);
            let api_use_modern_holidays = <bool>::sse_decode(&mut deserializer);
            let api_java =
                <crate::api::JavaJewishCalendarTestResults>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::test_jewish_calendar(
                        api_year,
                        api_month,
                        api_day,
                        api_in_israel,
                        api_is_mukaf_choma,
                        api_use_modern_holidays,
                        api_java,
                    );
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__timezones_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "timezones",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::timezones())?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>
);

// Section: dart2rust

impl SseDecode for ZmanimPreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::JavaJewishCalendarTestResults {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isUseModernHolidays = <bool>::sse_decode(deserializer);
        let mut var_getInIsrael = <bool>::sse_decode(deserializer);
        let mut var_getIsMukafChoma = <bool>::sse_decode(deserializer);
        let mut var_isBirkasHachamah = <bool>::sse_decode(deserializer);
        let mut var_getParshah = <Option<i32>>::sse_decode(deserializer);
        let mut var_getUpcomingParshah = <i32>::sse_decode(deserializer);
        let mut var_getSpecialShabbos = <Option<i32>>::sse_decode(deserializer);
        let mut var_getYomTovIndex = <i32>::sse_decode(deserializer);
        let mut var_isYomTov = <bool>::sse_decode(deserializer);
        let mut var_isYomTovAssurBemelacha = <bool>::sse_decode(deserializer);
        let mut var_isAssurBemelacha = <bool>::sse_decode(deserializer);
        let mut var_hasCandleLighting = <bool>::sse_decode(deserializer);
        let mut var_isTomorrowShabbosOrYomTov = <bool>::sse_decode(deserializer);
        let mut var_isErevYomTovSheni = <bool>::sse_decode(deserializer);
        let mut var_isAseresYemeiTeshuva = <bool>::sse_decode(deserializer);
        let mut var_isPesach = <bool>::sse_decode(deserializer);
        let mut var_isCholHamoedPesach = <bool>::sse_decode(deserializer);
        let mut var_isShavuos = <bool>::sse_decode(deserializer);
        let mut var_isRoshHashana = <bool>::sse_decode(deserializer);
        let mut var_isYomKippur = <bool>::sse_decode(deserializer);
        let mut var_isSuccos = <bool>::sse_decode(deserializer);
        let mut var_isHoshanaRabba = <bool>::sse_decode(deserializer);
        let mut var_isShminiAtzeres = <bool>::sse_decode(deserializer);
        let mut var_isSimchasTorah = <bool>::sse_decode(deserializer);
        let mut var_isCholHamoedSuccos = <bool>::sse_decode(deserializer);
        let mut var_isCholHamoed = <bool>::sse_decode(deserializer);
        let mut var_isErevYomTov = <bool>::sse_decode(deserializer);
        let mut var_isErevRoshChodesh = <bool>::sse_decode(deserializer);
        let mut var_isYomKippurKatan = <bool>::sse_decode(deserializer);
        let mut var_isBeHaB = <bool>::sse_decode(deserializer);
        let mut var_isTaanis = <bool>::sse_decode(deserializer);
        let mut var_isTaanisBechoros = <bool>::sse_decode(deserializer);
        let mut var_getDayOfChanukah = <Option<u8>>::sse_decode(deserializer);
        let mut var_isChanukah = <bool>::sse_decode(deserializer);
        let mut var_isPurim = <bool>::sse_decode(deserializer);
        let mut var_isRoshChodesh = <bool>::sse_decode(deserializer);
        let mut var_isMacharChodesh = <bool>::sse_decode(deserializer);
        let mut var_isShabbosMevorchim = <bool>::sse_decode(deserializer);
        let mut var_getDayOfOmer = <Option<u8>>::sse_decode(deserializer);
        let mut var_isTishaBav = <bool>::sse_decode(deserializer);
        let mut var_getMoladAsInstant = <i64>::sse_decode(deserializer);
        let mut var_getTchilasZmanKidushLevana3Days = <i64>::sse_decode(deserializer);
        let mut var_getTchilasZmanKidushLevana7Days = <i64>::sse_decode(deserializer);
        let mut var_getSofZmanKidushLevanaBetweenMoldos = <i64>::sse_decode(deserializer);
        let mut var_getSofZmanKidushLevana15Days = <i64>::sse_decode(deserializer);
        let mut var_getTekufasTishreiElapsedDays = <i32>::sse_decode(deserializer);
        let mut var_isIsruChag = <bool>::sse_decode(deserializer);
        return crate::api::JavaJewishCalendarTestResults {
            isUseModernHolidays: var_isUseModernHolidays,
            getInIsrael: var_getInIsrael,
            getIsMukafChoma: var_getIsMukafChoma,
            isBirkasHachamah: var_isBirkasHachamah,
            getParshah: var_getParshah,
            getUpcomingParshah: var_getUpcomingParshah,
            getSpecialShabbos: var_getSpecialShabbos,
            getYomTovIndex: var_getYomTovIndex,
            isYomTov: var_isYomTov,
            isYomTovAssurBemelacha: var_isYomTovAssurBemelacha,
            isAssurBemelacha: var_isAssurBemelacha,
            hasCandleLighting: var_hasCandleLighting,
            isTomorrowShabbosOrYomTov: var_isTomorrowShabbosOrYomTov,
            isErevYomTovSheni: var_isErevYomTovSheni,
            isAseresYemeiTeshuva: var_isAseresYemeiTeshuva,
            isPesach: var_isPesach,
            isCholHamoedPesach: var_isCholHamoedPesach,
            isShavuos: var_isShavuos,
            isRoshHashana: var_isRoshHashana,
            isYomKippur: var_isYomKippur,
            isSuccos: var_isSuccos,
            isHoshanaRabba: var_isHoshanaRabba,
            isShminiAtzeres: var_isShminiAtzeres,
            isSimchasTorah: var_isSimchasTorah,
            isCholHamoedSuccos: var_isCholHamoedSuccos,
            isCholHamoed: var_isCholHamoed,
            isErevYomTov: var_isErevYomTov,
            isErevRoshChodesh: var_isErevRoshChodesh,
            isYomKippurKatan: var_isYomKippurKatan,
            isBeHaB: var_isBeHaB,
            isTaanis: var_isTaanis,
            isTaanisBechoros: var_isTaanisBechoros,
            getDayOfChanukah: var_getDayOfChanukah,
            isChanukah: var_isChanukah,
            isPurim: var_isPurim,
            isRoshChodesh: var_isRoshChodesh,
            isMacharChodesh: var_isMacharChodesh,
            isShabbosMevorchim: var_isShabbosMevorchim,
            getDayOfOmer: var_getDayOfOmer,
            isTishaBav: var_isTishaBav,
            getMoladAsInstant: var_getMoladAsInstant,
            getTchilasZmanKidushLevana3Days: var_getTchilasZmanKidushLevana3Days,
            getTchilasZmanKidushLevana7Days: var_getTchilasZmanKidushLevana7Days,
            getSofZmanKidushLevanaBetweenMoldos: var_getSofZmanKidushLevanaBetweenMoldos,
            getSofZmanKidushLevana15Days: var_getSofZmanKidushLevana15Days,
            getTekufasTishreiElapsedDays: var_getTekufasTishreiElapsedDays,
            isIsruChag: var_isIsruChag,
        };
    }
}

impl SseDecode for Vec<ZmanimPreset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<ZmanimPreset>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<(i32, u8, u8)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<(i32, u8, u8)>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<(String, i64)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<(String, i64)>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for (i32, u8, u8) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <i32>::sse_decode(deserializer);
        let mut var_field1 = <u8>::sse_decode(deserializer);
        let mut var_field2 = <u8>::sse_decode(deserializer);
        return (var_field0, var_field1, var_field2);
    }
}

impl SseDecode for (String, i64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        let mut var_field1 = <i64>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__ZmanimPreset_name_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__add_days_to_jewish_date_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__add_months_to_jewish_date_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__add_years_to_jewish_date_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__calculate_zman_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__find_timezone_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__gregorian_date_to_jewish_date_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__java_jewish_calendar_test_results_new_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__jewish_date_to_gregorian_date_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__presets_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__test_jewish_calendar_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__timezones_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ZmanimPreset> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<ZmanimPreset> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ZmanimPreset>> for ZmanimPreset {
    fn into_into_dart(self) -> FrbWrapper<ZmanimPreset> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::JavaJewishCalendarTestResults {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.isUseModernHolidays.into_into_dart().into_dart(),
            self.getInIsrael.into_into_dart().into_dart(),
            self.getIsMukafChoma.into_into_dart().into_dart(),
            self.isBirkasHachamah.into_into_dart().into_dart(),
            self.getParshah.into_into_dart().into_dart(),
            self.getUpcomingParshah.into_into_dart().into_dart(),
            self.getSpecialShabbos.into_into_dart().into_dart(),
            self.getYomTovIndex.into_into_dart().into_dart(),
            self.isYomTov.into_into_dart().into_dart(),
            self.isYomTovAssurBemelacha.into_into_dart().into_dart(),
            self.isAssurBemelacha.into_into_dart().into_dart(),
            self.hasCandleLighting.into_into_dart().into_dart(),
            self.isTomorrowShabbosOrYomTov.into_into_dart().into_dart(),
            self.isErevYomTovSheni.into_into_dart().into_dart(),
            self.isAseresYemeiTeshuva.into_into_dart().into_dart(),
            self.isPesach.into_into_dart().into_dart(),
            self.isCholHamoedPesach.into_into_dart().into_dart(),
            self.isShavuos.into_into_dart().into_dart(),
            self.isRoshHashana.into_into_dart().into_dart(),
            self.isYomKippur.into_into_dart().into_dart(),
            self.isSuccos.into_into_dart().into_dart(),
            self.isHoshanaRabba.into_into_dart().into_dart(),
            self.isShminiAtzeres.into_into_dart().into_dart(),
            self.isSimchasTorah.into_into_dart().into_dart(),
            self.isCholHamoedSuccos.into_into_dart().into_dart(),
            self.isCholHamoed.into_into_dart().into_dart(),
            self.isErevYomTov.into_into_dart().into_dart(),
            self.isErevRoshChodesh.into_into_dart().into_dart(),
            self.isYomKippurKatan.into_into_dart().into_dart(),
            self.isBeHaB.into_into_dart().into_dart(),
            self.isTaanis.into_into_dart().into_dart(),
            self.isTaanisBechoros.into_into_dart().into_dart(),
            self.getDayOfChanukah.into_into_dart().into_dart(),
            self.isChanukah.into_into_dart().into_dart(),
            self.isPurim.into_into_dart().into_dart(),
            self.isRoshChodesh.into_into_dart().into_dart(),
            self.isMacharChodesh.into_into_dart().into_dart(),
            self.isShabbosMevorchim.into_into_dart().into_dart(),
            self.getDayOfOmer.into_into_dart().into_dart(),
            self.isTishaBav.into_into_dart().into_dart(),
            self.getMoladAsInstant.into_into_dart().into_dart(),
            self.getTchilasZmanKidushLevana3Days
                .into_into_dart()
                .into_dart(),
            self.getTchilasZmanKidushLevana7Days
                .into_into_dart()
                .into_dart(),
            self.getSofZmanKidushLevanaBetweenMoldos
                .into_into_dart()
                .into_dart(),
            self.getSofZmanKidushLevana15Days
                .into_into_dart()
                .into_dart(),
            self.getTekufasTishreiElapsedDays
                .into_into_dart()
                .into_dart(),
            self.isIsruChag.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::JavaJewishCalendarTestResults
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::JavaJewishCalendarTestResults>
    for crate::api::JavaJewishCalendarTestResults
{
    fn into_into_dart(self) -> crate::api::JavaJewishCalendarTestResults {
        self
    }
}

impl SseEncode for ZmanimPreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::JavaJewishCalendarTestResults {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.isUseModernHolidays, serializer);
        <bool>::sse_encode(self.getInIsrael, serializer);
        <bool>::sse_encode(self.getIsMukafChoma, serializer);
        <bool>::sse_encode(self.isBirkasHachamah, serializer);
        <Option<i32>>::sse_encode(self.getParshah, serializer);
        <i32>::sse_encode(self.getUpcomingParshah, serializer);
        <Option<i32>>::sse_encode(self.getSpecialShabbos, serializer);
        <i32>::sse_encode(self.getYomTovIndex, serializer);
        <bool>::sse_encode(self.isYomTov, serializer);
        <bool>::sse_encode(self.isYomTovAssurBemelacha, serializer);
        <bool>::sse_encode(self.isAssurBemelacha, serializer);
        <bool>::sse_encode(self.hasCandleLighting, serializer);
        <bool>::sse_encode(self.isTomorrowShabbosOrYomTov, serializer);
        <bool>::sse_encode(self.isErevYomTovSheni, serializer);
        <bool>::sse_encode(self.isAseresYemeiTeshuva, serializer);
        <bool>::sse_encode(self.isPesach, serializer);
        <bool>::sse_encode(self.isCholHamoedPesach, serializer);
        <bool>::sse_encode(self.isShavuos, serializer);
        <bool>::sse_encode(self.isRoshHashana, serializer);
        <bool>::sse_encode(self.isYomKippur, serializer);
        <bool>::sse_encode(self.isSuccos, serializer);
        <bool>::sse_encode(self.isHoshanaRabba, serializer);
        <bool>::sse_encode(self.isShminiAtzeres, serializer);
        <bool>::sse_encode(self.isSimchasTorah, serializer);
        <bool>::sse_encode(self.isCholHamoedSuccos, serializer);
        <bool>::sse_encode(self.isCholHamoed, serializer);
        <bool>::sse_encode(self.isErevYomTov, serializer);
        <bool>::sse_encode(self.isErevRoshChodesh, serializer);
        <bool>::sse_encode(self.isYomKippurKatan, serializer);
        <bool>::sse_encode(self.isBeHaB, serializer);
        <bool>::sse_encode(self.isTaanis, serializer);
        <bool>::sse_encode(self.isTaanisBechoros, serializer);
        <Option<u8>>::sse_encode(self.getDayOfChanukah, serializer);
        <bool>::sse_encode(self.isChanukah, serializer);
        <bool>::sse_encode(self.isPurim, serializer);
        <bool>::sse_encode(self.isRoshChodesh, serializer);
        <bool>::sse_encode(self.isMacharChodesh, serializer);
        <bool>::sse_encode(self.isShabbosMevorchim, serializer);
        <Option<u8>>::sse_encode(self.getDayOfOmer, serializer);
        <bool>::sse_encode(self.isTishaBav, serializer);
        <i64>::sse_encode(self.getMoladAsInstant, serializer);
        <i64>::sse_encode(self.getTchilasZmanKidushLevana3Days, serializer);
        <i64>::sse_encode(self.getTchilasZmanKidushLevana7Days, serializer);
        <i64>::sse_encode(self.getSofZmanKidushLevanaBetweenMoldos, serializer);
        <i64>::sse_encode(self.getSofZmanKidushLevana15Days, serializer);
        <i32>::sse_encode(self.getTekufasTishreiElapsedDays, serializer);
        <bool>::sse_encode(self.isIsruChag, serializer);
    }
}

impl SseEncode for Vec<ZmanimPreset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <ZmanimPreset>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<(i32, u8, u8)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <(i32, u8, u8)>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<(String, i64)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <(String, i64)>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for (i32, u8, u8) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.0, serializer);
        <u8>::sse_encode(self.1, serializer);
        <u8>::sse_encode(self.2, serializer);
    }
}

impl SseEncode for (String, i64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
        <i64>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_test_with_java_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_test_with_java_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZmanimPreset(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZmanimPreset>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
